package main

type Tag string

const (
	PROOF_OF_STAKE     Tag = "proof-of-stake"
	PROOF_OF_WORK      Tag = "proof-of-work"
	LIQUID_STAKING     Tag = "liquid-staking"
	LIGHT_CLIENTS      Tag = "light-clients"
	INTEROPERABILITY   Tag = "interoperability"
	WALLETS            Tag = "wallets"
	PAYMENT_CHANNELS   Tag = "payment-channels"
	ZERO_KNOWLEDGE     Tag = "zero-knowledge"
	SIGNATURES         Tag = "signatures"
	LIGHTNING_NETWORK  Tag = "lightning-network"
	SMART_CONTRACTS    Tag = "smart-contracts"
	PVSS               Tag = "pvss"
	RANDOMNESS         Tag = "randomness"
	CONSENSUS          Tag = "consensus"
	IDENTIFICATION     Tag = "identification"
	MPC                Tag = "mpc"
	PRIVACY            Tag = "privacy"
	FAIRNESS           Tag = "fairness"
	FRONT_RUNNING      Tag = "front-running"
	TIMELOCK           Tag = "timelock"
	UC                 Tag = "universal-composability"
	DEFI               Tag = "defi"
	COMMITMENTS        Tag = "commitments"
	OBLIVIOUS_TRANSFER Tag = "oblivious-transfer"
	ANONYMITY          Tag = "anonymity"
	MEV                Tag = "mev"
	YOSO               Tag = "yoso"
	ROM                Tag = "random-oracle"
	HOMOMORPHISM       Tag = "homomorphism"
	BITCOIN            Tag = "bitcoin"
	VOTING             Tag = "voting"
	SHARDING           Tag = "sharding"
	VDF                Tag = "verifiable-delay-functions"
	WITNESS_ENCRYPTION Tag = "witness-encryption"
	DECENTRALIZATION   Tag = "decentralization"
	TIMELINESS         Tag = "timeliness"
	SUPERSAFETY        Tag = "supersafety"
)

var TagToColor = map[Tag]string{
	PROOF_OF_STAKE:     "#e4cbf4",
	PROOF_OF_WORK:      "#ffc0c0",
	LIQUID_STAKING:     "#e6e6fa",
	LIGHT_CLIENTS:      "#fff3b0",
	INTEROPERABILITY:   "#a5d0ec",
	WALLETS:            "#e1ddad",
	PAYMENT_CHANNELS:   "#c5e2b5",
	ZERO_KNOWLEDGE:     "#e0b5e9",
	SIGNATURES:         "#fae2d9",
	LIGHTNING_NETWORK:  "#d4e2d4",
	SMART_CONTRACTS:    "#f9e6fa",
	PVSS:               "#d9e4f5",
	RANDOMNESS:         "#d1f0fc",
	CONSENSUS:          "#e8d4b3",
	IDENTIFICATION:     "#f6f0c4",
	MPC:                "#e5dcca",
	PRIVACY:            "#abc4c7",
	FAIRNESS:           "#d0f5d0",
	FRONT_RUNNING:      "#ffe4e9",
	TIMELOCK:           "#b3e6ff",
	UC:                 "#ffd9cc",
	DEFI:               "#e8ccf5",
	COMMITMENTS:        "#ffead4",
	OBLIVIOUS_TRANSFER: "#a8e8e8",
	ANONYMITY:          "#c7d2d9",
	MEV:                "#f3b0e0",
	YOSO:               "#ffd1b3",
	ROM:                "#8cd1a4",
	HOMOMORPHISM:       "#e6a1a1",
	BITCOIN:            "#ffb732",
	VOTING:             "#d4b39e",
	SHARDING:           "#b0a8f5",
	VDF:                "#c2c2d1",
	WITNESS_ENCRYPTION: "#ffd4e6",
	DECENTRALIZATION:   "#f0deba",
	TIMELINESS:         "#fabf8b",
	SUPERSAFETY:        "#1fea33",
}

var ResearchPapers []ResearchPaper = []ResearchPaper{
	{
		Handle:         "timeliness",
		Name:           "On-Chain Timestamps Are Accurate",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2024,
		Authors:        []string{"Apostolos Tzinas", "Srivatsan Sridhar", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2023/1648.pdf",
		Tags:           []Tag{TIMELINESS, SUPERSAFETY},
	},
	{
		Handle:         "popos",
		Name:           "Proofs of Proof-of-Stake with Sublinear Complexity",
		Conference:     "ACM Advances in Financial Technologies",
		ConferenceYear: 2023,
		Authors:        []string{"Shresth Agrawal", "Joachim Neu", "Ertem Nusret Tas", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/2209.08673.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, LIGHT_CLIENTS, INTEROPERABILITY},
	},
	{
		Handle:         "liquid-staking",
		Name:           "The Principal–Agent Problem in Liquid Staking",
		Conference:     "Financial Cryptography and Data Security, Workshop in Trusted Smart Contracts",
		ConferenceYear: 2023,
		Authors:        []string{"Apostolos Tzinas", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2023/605.pdf",
		Tags:           []Tag{LIQUID_STAKING},
	},
	{
		Handle:         "nipopow",
		Name:           "Non-Interactive Proofs of Proof-of-Work",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2020,
		Authors:        []string{"Aggelos Kiayias", "Andrew Miller", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2017/963.pdf",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
	},
	{
		Handle:         "ouroboros",
		Name:           "Ouroboros: A provably secure proof-of-stake blockchain protocol",
		Conference:     "Advances in Cryptology–CRYPTO",
		ConferenceYear: 2017,
		Authors:        []string{"Aggelos Kiayias", "Alexander Russell", "Bernardo David", "Roman Oliynykov"},
		Url:            "https://eprint.iacr.org/2016/889.pdf",
		Tags:           []Tag{PROOF_OF_STAKE},
	},
	{
		Handle:         "hardware-wallets",
		Name:           "A formal treatment of hardware wallets",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2019,
		Authors:        []string{"Myrto Arapinis", "Andriana Gkaniatsou", "Dimitris Karakostas", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2019/034.pdf",
		Tags:           []Tag{WALLETS},
	},
	{
		Handle:         "brick",
		Name:           "Brick: Asynchronous Incentive-Compatible Payment Channels",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2021,
		Authors:        []string{"Zeta Avarikioti", "Eleftherios Kokoris-Kogias", "Roger Wattenhofer", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1905.11360.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
	},
	{
		Handle:         "zk-arguments",
		Name:           "Efficient Zero-Knowledge Arguments for Arithmetic Circuits in the Discrete Log Setting",
		Conference:     "Advances in Cryptology–EUROCRYPT",
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Jens Groth", "Christophe Petit"},
		Url:            "https://eprint.iacr.org/2016/263.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
	},
	{
		Handle:         "dynamic-group-signatures",
		Name:           "Foundations of Fully Dynamic Group Signatures",
		Conference:     "International Conference on Applied Cryptography and Network Security",
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth"},
		Url:            "https://eprint.iacr.org/2016/368.pdf",
		Tags:           []Tag{SIGNATURES},
	},
	{
		Handle:         "lightning-network-security",
		Name:           "A Composable Security Treatment of the Lightning Network",
		Conference:     "IEEE Computer Security Foundations Symposium",
		ConferenceYear: 2020,
		Authors:        []string{"Aggelos Kiayias", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://eprint.iacr.org/2019/778.pdf",
		Tags:           []Tag{LIGHTNING_NETWORK},
	},
	{
		Handle:         "ouroboros-praos",
		Name:           "Ouroboros Praos: An adaptively-secure, semi-synchronous proof-of-stake blockchain",
		Conference:     "Advances in Cryptology–EUROCRYPT",
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Peter Gaži", "Aggelos Kiayias", "Alexander Russell"},
		Url:            "https://eprint.iacr.org/2017/573.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, CONSENSUS},
	},
	{
		Handle:         "scape",
		Name:           "SCRAPE: Scalable randomness attested by public entities",
		Conference:     "Applied Cryptography and Network Security–ACNS",
		ConferenceYear: 2017,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2017/216.pdf",
		Tags:           []Tag{PVSS, RANDOMNESS},
	},
	{
		Handle:         "constant-sps",
		Name:           "Constant-size structure-preserving signatures: Generic constructions and simple assumptions",
		Conference:     "Theory and Application of Cryptology and Information Security–ASIACRYPT",
		ConferenceYear: 2012,
		Authors:        []string{"Masayuki Abe", "Melissa Chase", "Bernardo David", "Markulf Kohlweiss", "Ryo Nishimaki", "Miyako Ohkubo"},
		Url:            "https://eprint.iacr.org/2012/285.pdf",
		Tags:           []Tag{SIGNATURES},
	},
	{
		Handle:         "tagged-ots",
		Name:           "Tagged one-time signatures: Tight security and optimal tag size",
		Conference:     "Public-Key Cryptography–PKC",
		ConferenceYear: 2013,
		Authors:        []string{"Masayuki Abe", "Bernardo David", "Markulf Kohlweiss", "Ryo Nishimaki", "Miyako Ohkubo"},
		Url:            "https://eprint.iacr.org/2015/311.pdf",
		Tags:           []Tag{SIGNATURES},
	},
	{
		Handle:         "internet-banking-attacks",
		Name:           "A Formal Classification of Internet Banking Attacks and Vulnerabilities",
		Conference:     "International Journal of Computer Science & Information Technology–IJCSIT",
		ConferenceYear: 2011,
		Authors:        []string{"Laerte Peotta", "Marcelo Holtz", "Bernardo David", "Flavio Deus", "RT de Sousa"},
		Url:            "https://airccse.org/journal/jcsit/0211ijcsit13.pdf",
		Tags:           []Tag{IDENTIFICATION},
	},
	{
		Handle:         "albatross",
		Name:           "ALBATROSS: Publicly AttestabLe BATched Randomness Based On Secret Sharing",
		Conference:     "Theory and Application of Cryptology and Information Security–ASIACRYPT",
		ConferenceYear: 2020,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2020/644.pdf",
		Tags:           []Tag{RANDOMNESS, PVSS},
	},
	{
		Handle:         "p2dex",
		Name:           "P2DEX: privacy-preserving decentralized cryptocurrency exchange",
		Conference:     "Applied Cryptography and Network Security–ACNS",
		ConferenceYear: 2021,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2021/283.pdf",
		Tags:           []Tag{MPC, PRIVACY, FAIRNESS, FRONT_RUNNING},
	},
	{
		Handle:         "tardis",
		Name:           "TARDIS: a foundation of time-lock puzzles in UC",
		Conference:     "Advances in Cryptology–EUROCRYPT",
		ConferenceYear: 2021,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley", "Jesper Buus Nielsen", "Sabine Oechsner"},
		Url:            "https://eprint.iacr.org/2020/537.pdf",
		Tags:           []Tag{TIMELOCK, UC},
	},
	{
		Handle:         "uc-commitments",
		Name:           "Rate-1, linear time and additively homomorphic UC commitments",
		Conference:     "Annual International Cryptology Conference–CRYPTO",
		ConferenceYear: 2016,
		Authors:        []string{"Ignacio Cascudo", "Ivan Damgård", "Bernardo David", "Nico Döttling", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2016/137.pdf",
		Tags:           []Tag{COMMITMENTS, UC},
	},
	{
		Handle:         "insured-mpc",
		Name:           "Insured MPC: Efficient secure computation with financial penalties",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2020,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2018/942.pdf",
		Tags:           []Tag{MPC, FAIRNESS, UC},
	},
	{
		Handle:         "map-reduce-ids",
		Name:           "Building Scalable Distributed Intrusion Detection Systems Based on the MapReduce Framework",
		Conference:     "Revista Telecommun",
		ConferenceYear: 2011,
		Authors:        []string{"Marcelo D Holtz", "Bernardo David", "Rafael Timóteo de Sousa Júnior"},
		Url:            "https://www.academia.edu/download/61520800/Building_Scalable_Distributed_Intrusion_20191215-6958-g7aso0.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "vss-homomorphic-uc-commitments",
		Name:           "Compact VSS and efficient homomorphic UC commitments",
		Conference:     "Advances in Cryptology–ASIACRYPT",
		ConferenceYear: 2014,
		Authors:        []string{"Ivan Damgård", "Bernardo David", "Irene Giacomelli", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2014/370.pdf",
		Tags:           []Tag{UC, COMMITMENTS, HOMOMORPHISM},
	},
	{
		Handle:         "lpn-uc-transfer",
		Name:           "Universally composable oblivious transfer based on a variant of LPN",
		Conference:     "Cryptology and Network Security–CANS",
		ConferenceYear: 2014,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Anderson CA Nascimento"},
		Url:            "https://dowsley.net/pdf/CANS-DavDowNas14.pdf",
		Tags:           []Tag{UC, OBLIVIOUS_TRANSFER},
	},
	{
		Handle:         "uc-rom-oblivious-transfer",
		Name:           "A Framework for Efficient Adaptively Secure Composable Oblivious Transfer in the ROM",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2017,
		Authors:        []string{"Paulo SLM Barreto", "Bernardo David", "Rafael Dowsley", "Kirill Morozov", "Anderson CA Nascimento"},
		Url:            "https://eprint.iacr.org/2017/993.pdf",
		Tags:           []Tag{UC, ROM, OBLIVIOUS_TRANSFER},
	},
	{
		Handle:         "private-ml-classification",
		Name:           "Efficient unconditionally secure comparison and privacy preserving machine learning classification protocols",
		Conference:     "Provable Security–PROVSEC",
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Raj Katti", "Anderson CA Nascimento"},
		Url:            "https://dowsley.net/pdf/PROVSEC-DDKN15.pdf",
		Tags:           []Tag{PRIVACY},
	},
	{
		Handle:         "homomorphic-uc-commitments",
		Name:           "Additively Homomorphic UC commitments with Optimal Amortized Overhead",
		Conference:     "Practice and Theory in Public-Key Cryptography–PKC",
		ConferenceYear: 2015,
		Authors:        []string{"Ignacio Cascudo Pueyo", "Ivan Bjerre Damgård", "Bernardo Machado David", "Irene Giacomelli", "Jesper Buus Nielsen", "Roberto Trifiletti"},
		Url:            "https://eprint.iacr.org/2014/829.pdf",
		Tags:           []Tag{UC, COMMITMENTS},
	},
	{
		Handle:         "craft",
		Name:           "CRAFT: Composable Randomness Beacons and Output-Independent Abort MPC From Time",
		Conference:     "Practice and Theory in Public-Key Cryptography–PKC",
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley", "Ravi Kishore", "Jesper Buus Nielsen", "Sabine Oechsner"},
		Url:            "https://eprint.iacr.org/2020/784.pdf",
		Tags:           []Tag{UC, TIMELOCK, VDF, RANDOMNESS},
	},
	{
		Handle:         "front-running-sok",
		Name:           "SoK: Mitigation of front-running in decentralized finance",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2022,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen", "Lorenzo Gentile"},
		Url:            "https://eprint.iacr.org/2021/1628.pdf",
		Tags:           []Tag{DEFI, FRONT_RUNNING, MEV},
	},
	{
		Handle:         "anonymous-timelock",
		Name:           "Encryption to the future: a paradigm for sending secret messages to future (anonymous) committees",
		Conference:     "Theory and Application of Cryptology and Information Security–ASIACRYPT",
		ConferenceYear: 2022,
		Authors:        []string{"Matteo Campanelli", "Bernardo David", "Hamidreza Khoshakhlagh", "Anders Konring", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2021/1423.pdf",
		Tags:           []Tag{TIMELOCK, WITNESS_ENCRYPTION},
	},
	{
		Handle:         "gearbox",
		Name:           "GearBox: An Efficient UC Sharded Ledger Leveraging the Safety-Liveness Dichotomy.",
		Conference:     "International Association for Cryptologic Research 2021–ACM CCS",
		ConferenceYear: 2022,
		Authors:        []string{"Bernardo David", "Bernardo Magri", "Christian Matt", "Jesper Buus Nielsen", "Daniel Tschudi"},
		Url:            "https://eprint.iacr.org/2021/211.pdf",
		Tags:           []Tag{UC, SHARDING},
	},
	{
		Handle:         "kaleidoscope",
		Name:           "Kaleidoscope: An efficient poker protocol with payment distribution and penalty enforcement",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2017/899.pdf",
		Tags:           []Tag{MPC},
	},
	{
		Handle:         "uc-private-linear-algebra",
		Name:           "Unconditionally secure, universally composable privacy preserving linear algebra",
		Conference:     "IEEE Transactions on Information Forensics and Security",
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Jeroen van de Graaf", "Davidson Marques", "Anderson CA Nascimento", "Adriana CB Pinto"},
		Url:            "https://dowsley.net/pdf/IEEEIFS-DDGM+16.pdf",
		Tags:           []Tag{UC, PRIVACY},
	},
	{
		Handle:         "yolo-yoso",
		Name:           "YOLO YOSO: Fast and simple encryption and secret sharing in the YOSO model",
		Conference:     "Theory and Application of Cryptology and Information Security–ASIACRYPT",
		ConferenceYear: 2022,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David", "Lydia Garms", "Anders Konring"},
		Url:            "https://eprint.iacr.org/2022/242.pdf",
		Tags:           []Tag{PVSS, YOSO, ANONYMITY},
	},
	{
		Handle:         "uc-oblivious-transfer",
		Name:           "Universally composable oblivious transfer from lossy encryption and the McEliece assumptions",
		Conference:     "Information Theoretic Security–ICITS",
		ConferenceYear: 2012,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Jörn Müller-Quade"},
		Url:            "https://link.springer.com/chapter/10.1007/978-3-642-32284-6_5",
		Tags:           []Tag{UC, OBLIVIOUS_TRANSFER},
	},
	{
		Handle:         "honeypot-blind-malicious-activity-detection",
		Name:           "Blind automatic malicious activity detection in honeypot data",
		Conference:     "International Conference on Forensic Computer Science–ICoFCS",
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "JPCL da Costa", "Anderson CA Nascimento", "D Amaral", "MD Holtz", "RT de Sousa Jr"},
		Url:            "https://lasp.unb.br/wp-content/uploads/papers/ICoFCS2011-PP16.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "eagle",
		Name:           "Eagle: Efficient privacy preserving smart contracts",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2022/1435.pdf",
		Tags:           []Tag{SMART_CONTRACTS, MPC},
	},
	{
		Handle:         "uc-homomorphic-commitments",
		Name:           "Efficient UC Commitment Extension with Homomorphism for Free (and Applications)",
		Conference:     "Theory and Application of Cryptology and Information Security–ASIACRYPT",
		ConferenceYear: 2019,
		Authors:        []string{"Ignacio Cascudo", "Ivan Damgård", "Bernardo David", "Nico Döttling", "Rafael Dowsley", "Irene Giacomelli"},
		Url:            "https://eprint.iacr.org/2018/983.pdf",
		Tags:           []Tag{UC, HOMOMORPHISM},
	},
	{
		Handle:         "royale",
		Name:           "ROYALE: a framework for universally composable card games with financial rewards and penalties enforcement",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2019,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2018/157.pdf",
		Tags:           []Tag{UC, FAIRNESS},
	},
	{
		Handle:         "mars",
		Name:           "MARS: Monetized Ad-hoc Routing System (A Position Paper)",
		Conference:     "Workshop on Cryptocurrencies and Blockchains for Distributed Systems–CryBlock",
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://dl.acm.org/doi/10.1145/3211933.3211948",
		Tags:           []Tag{},
	},
	{
		Handle:         "improved-honeypot-blind-malicious-activity-detection",
		Name:           "Improved blind automatic malicious activity detection in honeypot data",
		Conference:     "Forensic Computer Science–ICoFCS",
		ConferenceYear: 2012,
		Authors:        []string{"JPCL da Costa", "Edison Pignaton de Freitas", "Bernardo Machado David", "AM Rubio Serrano", "Dino Amaral", "RT Sousa Júnior"},
		Url:            "http://www.icofcs.org/2012/ICoFCS2012_08.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "fast",
		Name:           "FAST: Fair Auctions via Secret Transactions",
		Conference:     "Applied Cryptography and Network Security–ACNS",
		ConferenceYear: 2022,
		Authors:        []string{"Bernardo David", "Lorenzo Gentile", "Mohsen Pourpouneh"},
		Url:            "https://eprint.iacr.org/2021/264.pdf",
		Tags:           []Tag{FAIRNESS, PRIVACY},
	},
	{
		Handle:         "uc-private-proximity-testing",
		Name:           "Universally composable private proximity testing",
		Conference:     "Provable Security–PROVSEC",
		ConferenceYear: 2011,
		Authors:        []string{"Rafael Tonicelli", "Bernardo Machado David", "Vinícius de Morais Alves"},
		Url:            "https://link.springer.com/chapter/10.1007/978-3-642-24316-5_16",
		Tags:           []Tag{UC, PRIVACY},
	},
	{
		Handle:         "secure-sso",
		Name:           "A framework for secure single sign-on",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Rafael Tonicelli"},
		Url:            "https://eprint.iacr.org/2011/246.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "mt-random",
		Name:           "Mt. Random: Multi-tiered randomness beacons",
		Conference:     "Applied Cryptography and Network Security–ACNS",
		ConferenceYear: 2023,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David", "Omer Shlomovits", "Denis Varlakov"},
		Url:            "https://eprint.iacr.org/2021/1096.pdf",
		Tags:           []Tag{RANDOMNESS, PVSS},
	},
	{
		Handle:         "oblivious-transfer-from-mceliece",
		Name:           "Efficient fully simulatable oblivious transfer from the McEliece assumptions",
		Conference:     "IEICE Transactions on Fundamentals of Electronics, Communications and Computer Sciences",
		ConferenceYear: 2012,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Rafael T de Sousa"},
		Url:            "https://ieeexplore.ieee.org/document/6089575",
		Tags:           []Tag{},
	},
	{
		Handle:         "papr",
		Name:           "PAPR: Publicly auditable privacy revocation for anonymous credentials",
		Conference:     "Cryptographers' Track at the RSA Conference",
		ConferenceYear: 2023,
		Authors:        []string{"Joakim Brorsson", "Bernardo David", "Lorenzo Gentile", "Elena Pagnin", "Paul Stankovski Wagner"},
		Url:            "https://eprint.iacr.org/2023/137.pdf",
		Tags:           []Tag{PRIVACY},
	},
	{
		Handle:         "generalizing-mpc",
		Name:           "Generalizing efficient multiparty computation",
		Conference:     "Information Theoretic Security–ICITS",
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo M David", "Ryo Nishimaki", "Samuel Ranellucci", "Alain Tapp"},
		Url:            "https://eprint.iacr.org/2015/135.pdf",
		Tags:           []Tag{MPC, OBLIVIOUS_TRANSFER, UC},
	},
	{
		Handle:         "pca-based-malicious-activity-detection",
		Name:           "A Parallel Approach to PCA Based Malicious Activity Detection in Distributed Honeypot Data",
		Conference:     "Brazilian Association of High Technology Experts–ABEAT",
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "João Paulo Carvalho Lustosa da Costa", "Anderson Clayton Alves Nascimento", "Marcelo Dias Holtz", "Dino Macedo Amaral", "Rafael Timóteo de Sousa Júnior"},
		Url:            "http://www.realp.unb.br/jspui/bitstream/10482/10985/1/ARTIGO_ParallelApproachPCA.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "uc-verifiability-without-adaptivity-or-zk",
		Name:           "(Public) Verifiability for Composable Protocols Without Adaptivity or Zero-Knowledge",
		Conference:     "Provable Security–PROVSEC",
		ConferenceYear: 2022,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2020/207.pdf",
		Tags:           []Tag{UC},
	},
	{
		Handle:         "21",
		Name:           "21-bringing down the complexity: fast composable protocols for card games without secret state",
		Conference:     "Information Security and Privacy–ACISP",
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2018/303.pdf",
		Tags:           []Tag{MPC, UC},
	},
	{
		Handle:         "bayesian-trust-model-for-mac-in-802-15-4",
		Name:           "A Bayesian Trust Model for the MAC Layer in IEEE 802.15.4 Networks",
		Conference:     "International Information and Telecommunication Technologies Symposium–I2TS",
		ConferenceYear: 2010,
		Authors:        []string{"Bernardo Machado David", "Rafael Timoteo de Sousa Jr"},
		Url:            "http://www.inf.ufsc.br/~bosco.sobral/downloads/I2TS%202010%20CD%20Proceedings/www.i2ts.org/papers/full_english/78855_1.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "sok-privacy-in-finance",
		Name:           "SoK: Privacy-Enhancing Technologies in Finance",
		Conference:     "Advances in Financial Technologies–AFT",
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2023/122.pdf",
		Tags:           []Tag{DEFI, MPC, PRIVACY, ZERO_KNOWLEDGE},
	},
	{
		Handle:         "trust-model-for-mac-in-lr-wpans",
		Name:           "A Context-Dependent Trust Model for the MAC Layer in LR-WPANs",
		Conference:     "International Journal of Computer Science and Engineering–IJCSE",
		ConferenceYear: 2010,
		Authors:        []string{"Bernardo M David", "Beatriz Santana", "Laerte Peotta", "Marcelo D Holtz", "Rafael Timóteo de Sousa Jr"},
		Url:            "https://www.researchgate.net/profile/Rafael-De-Sousa-Junior/publication/50235175_A_Context-Dependent_Trust_Model_for_the_MAC_Layer_in_LR-WPANs_Bernardo_M_David_Beatriz_Santana_Laerte_Peotta_Marcelo_D_Holtz/links/549081910cf2d1800d866a6d/A-Context-Dependent-Trust-Model-for-the-MAC-Layer-in-LR-WPANs-Bernardo-M-David-Beatriz-Santana-Laerte-Peotta-Marcelo-D-Holtz.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "mpc-over-layered-graphs",
		Name:           "Perfect MPC over Layered Graphs",
		Conference:     "Annual International Cryptology Conference–CRYPTO",
		ConferenceYear: 2023,
		Authors:        []string{"Bernardo David", "Giovanni Deligios", "Aarushi Goel", "Yuval Ishai", "Anders Konring", "Eyal Kushilevitz", "Chen-Da Liu-Zhang", "Varun Narayanan"},
		Url:            "https://eprint.iacr.org/2023/330.pdf",
		Tags:           []Tag{MPC, YOSO},
	},
	{
		Handle:         "uc-oblivious-transfer-from-cdh",
		Name:           "Efficient Composable Oblivious Transfer from CDH in the Global Random Oracle Model",
		Conference:     "Cryptology and Network Security–CANS",
		ConferenceYear: 2020,
		Authors:        []string{"Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2020/1291.pdf",
		Tags:           []Tag{OBLIVIOUS_TRANSFER, UC},
	},
	{
		Handle:         "map-reduce-intrusion-detection-architecture",
		Name:           "An architecture for distributed Network Intrusion Detection Based on the Map-Reduce Framework",
		Conference:     "Proceedings of the International Workshop on Telecommunications–IWT",
		ConferenceYear: 2011,
		Authors:        []string{"Marcelo D Holtz", "Bernardo M David", "Laerte Peotta", "RT de Sousa Junior"},
		Url:            "https://www.researchgate.net/publication/52011678_An_architecture_for_distributed_Network_Intrusion_Detection_Based_on_the_Map-Reduce_Framework",
		Tags:           []Tag{},
	},
	{
		Handle:         "decentralized-info-market",
		Name:           "A Decentralized Information Marketplace Preserving Input and Output Privacy",
		Conference:     "Proceedings of the Second ACM Data Economy Workshop",
		ConferenceYear: 2023,
		Authors:        []string{"Steven Golob", "Sikha Pentyala", "Rafael Dowsley", "Bernardo David", "Mario Larangeira", "Martine De Cock", "Anderson Nascimento"},
		Url:            "https://dl.acm.org/doi/pdf/10.1145/3600046.3600047",
		Tags:           []Tag{PRIVACY, MPC},
	},
	{
		Handle:         "fairpos",
		Name:           "FairPoS: Input Fairness in Permissionless Consensus",
		Conference:     "5th Conference on Advances in Financial Technologies–AFT",
		ConferenceYear: 2023,
		Authors:        []string{"James Hsin-yu Chiang", "Bernardo David", "Ittay Eyal", "Tiantian Gong"},
		Url:            "https://eprint.iacr.org/2022/1442.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, FRONT_RUNNING},
	},
	{
		Handle:         "co-differential-privacy",
		Name:           "Correlated-Output Differential Privacy and Applications to Dark Pools",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2023,
		Authors:        []string{"James Hsin-yu Chiang", "Bernardo David", "Mariana Gama", "Christian Janos Lebeda"},
		Url:            "https://eprint.iacr.org/2023/943.pdf",
		Tags:           []Tag{DEFI, MPC},
	},
	{
		Handle:         "voting-diff-privacy",
		Name:           "Local Differential Privacy in Voting",
		Conference:     "The Italian Conference on CyberSecurity–ITASEC",
		ConferenceYear: 2023,
		Authors:        []string{"Rosario Giustolisi", "Bernardo David", "Victor Mortensen", "Morten Pedersen"},
		Url:            "https://ceur-ws.org/Vol-3488/paper16.pdf",
		Tags:           []Tag{VOTING, PRIVACY},
	},
	{
		Handle:         "updatable-private-blueprints",
		Name:           "Updatable Privacy-Preserving Blueprints",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2023,
		Authors:        []string{"Bernardo David", "Felix Engelmann", "Tore Frederiksen", "Markulf Kohlweiss", "Elena Pagnin", "Mikhail Volkhov"},
		Url:            "https://eprint.iacr.org/2023/1787.pdf",
		Tags:           []Tag{PRIVACY, ZERO_KNOWLEDGE},
	},
	{
		Handle:         "pvss-over-class-groups",
		Name:           "Publicly Verifiable Secret Sharing over Class Groups and Applications to DKG and YOSO",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2023,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2023/1651.pdf",
		Tags:           []Tag{PVSS, MPC, YOSO},
	},
	{
		Handle:         "cascade",
		Name:           "CaSCaDE: (Time-Based) Cryptography from Space Communications DElay",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Elena Pagnin", "Akira Takahashi"},
		Url:            "https://eprint.iacr.org/2023/405.pdf",
		Tags:           []Tag{TIMELOCK, VDF},
	},
	{
		Handle:     "uc-homomorphic-commitments",
		Name:       "A Framework For Efficient Homomorphic Universally Composable Commitments",
		Conference: "Dissertation 2016, Department of Computer Science, University of Aarhus",
		Authors:    []string{"Bernardo Machado David"},
		Url:        "https://pure.au.dk/ws/portalfiles/portal/114777545/Bernardo_Machado_Davids_thesis.pdf",
		Tags:       []Tag{UC, COMMITMENTS},
	},
	{
		Handle:         "uc-committed-oblivious-transfer-with-trusted-initializer",
		Name:           "Universally Composable Committed Oblivious Transfer With A Trusted Initializer",
		Conference:     "Anais do XII Simpósio Brasileiro em Segurança da Informação e de Sistemas Computacionais",
		ConferenceYear: 2012,
		Authors:        []string{"Adriana CB Pinto", "Bernardo Machado David", "Jeroen van de Graaf", "Anderson CA Nascimento"},
		Url:            "https://sol.sbc.org.br/index.php/sbseg/article/download/20541/20368",
		Tags:           []Tag{OBLIVIOUS_TRANSFER, UC},
	},
	{
		Handle:         "fully-simulatable-oblivious-transfer",
		Name:           "Obtaining Efficient Fully Simulatable Oblivious Transfer from General Assumptions",
		Conference:     "Anais do XI Simpósio Brasileiro em Segurança da Informação e de Sistemas Computacionais",
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo M David", "Anderson CA Nascimento", "Rafael Tonicelli"},
		Url:            "https://sol.sbc.org.br/index.php/sbseg/article/download/20567/20394",
		Tags:           []Tag{OBLIVIOUS_TRANSFER},
	},
	{
		Handle:         "cerberus-channels",
		Name:           "Cerberus Channels: Incentivizing Watchtowers for Bitcoin",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2020,
		Authors:        []string{"Zeta Avarikioti", "Orfeas Stefanos Thyfronitis Litos", "Roger Wattenhofer"},
		Url:            "https://eprint.iacr.org/2019/1092.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
	},
	{
		Handle:         "divide-and-scale",
		Name:           "Divide & Scale: Formalization and Roadmap to Robust Sharding",
		Conference:     "International Colloquium on Structural Information and Communication Complexity",
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Antoine Desjardins", "Lefteris Kokoris-Kogias", "Roger Wattenhofer"},
		Url:            "https://drive.google.com/file/d/1EKbY-8rCNj7zDTuVYcj5WAiFX2hYwqai/view",
		Tags:           []Tag{SHARDING},
	},
	{
		Handle:         "secure-and-efficient-payment-channels",
		Name:           "Towards secure and efficient payment channels",
		Conference:     "ArXiv",
		ConferenceYear: 2018,
		Authors:        []string{"Georgia Avarikioti", "Felix Laufenberg", "Jakub Sliwinski", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1811.12740.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
	},
	{
		Handle:         "ride-the-lightning",
		Name:           "Ride the lightning: The game theory of payment channels",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2020,
		Authors:        []string{"Zeta Avarikioti", "Lioba Heimbach", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1912.04797.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
	},
	{
		Handle:         "payment-network-with-fees",
		Name:           "Payment network design with fees",
		Conference:     "Data Privacy Management, Cryptocurrencies and Blockchain Technology–ESORICS",
		ConferenceYear: 2018,
		Authors:        []string{"Georgia Avarikioti", "Gerrit Janssen", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1810.07585.pdf",
		Tags:           []Tag{}, //keywords:  blockchain, layer 2, channels, lightning protocol

	},
	{
		Handle:         "darknet",
		Name:           "Structure and content of the visible Darknet",
		Conference:     "ArXiv",
		ConferenceYear: 2018,
		Authors:        []string{"Georgia Avarikioti", "Roman Brunner", "Aggelos Kiayias", "Roger Wattenhofer", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1811.01348.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "fnf-bft",
		Name:           "FnF-BFT: A BFT Protocol with Provable Performance Under Attack",
		Conference:     "International Colloquium on Structural Information and Communication Complexity–SIROCCO",
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Lioba Heimbach", "Roland Schmid", "Laurent Vanbever", "Roger Wattenhofer", "Patrick Wintermeyer"},
		Url:            "https://tik-old.ee.ethz.ch/file/34168cbbbcfa75bf48c87a84844b3ae9/FnF_BFT__SIROCCO_2023_-1.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "bitcoin-temporary-dishonest-majority",
		Name:           "Bitcoin Security under Temporary Dishonest Majority",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2019,
		Authors:        []string{"Georgia Avarikioti", "Lukas Käppeli", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1908.00427.pdf",
		Tags:           []Tag{}, //keywords : Bitcoin, Security, Dishonest Majority, Offline Players, Sleepy Model
	},
	{
		Handle:         "hide-and-seek",
		Name:           "Hide & Seek: Privacy-Preserving Rebalancing on Payment Channel Networks",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2022,
		Authors:        []string{"Zeta Avarikioti", "Krzysztof Pietrzak", "Iosif Salem", "Stefan Schmid", "Samarth Tiwari", "Michelle Yeo"},
		Url:            "https://arxiv.org/pdf/2110.08848.pdf",
		Tags:           []Tag{}, //keywords : Payment Channel Networks, Privacy, Rebalancing.
	},
	{
		Handle:     "tx-chain",
		Name:       "TxChain: Efficient Cryptocurrency Light Clients via Contingent Transaction Aggregation",
		Conference: "DPM 2020, CBT 2020: Data Privacy Management, Cryptocurrencies and Blockchain Technology",
		Authors:    []string{"Alexei Zamyatin", "Zeta Avarikioti", "Daniel Perez", "William J. Knottenbelt"},
		Url:        "https://eprint.iacr.org/2020/580.pdf",
		Tags:       []Tag{LIGHT_CLIENTS},
	},
	{
		Handle:     "payment-networks-as-creation-games",
		Name:       "Payment Networks as Creation Games",
		Conference: "DPM 2019, CBT 2019: Data Privacy Management, Cryptocurrencies and Blockchain Technology",
		Authors:    []string{"Georgia Avarikioti", "Rolf Scheuner", "Roger Wattenhofer"},
		Url:        "https://arxiv.org/pdf/1908.00436.pdf",
		Tags:       []Tag{PAYMENT_CHANNELS},
	},
	{
		Handle:         "algorithmic-channel-design",
		Name:           "Algorithmic channel design",
		Conference:     "International Symposium on Algorithms and Computation–ISAAC",
		ConferenceYear: 2018,
		Authors:        []string{"Georgia Avarikioti", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/336835/1/LIPIcs-ISAAC-2018-16.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
	},
	{
		Handle:     "high-dimensional-approximate-r-nets",
		Name:       "High-dimensional approximate r-nets",
		Conference: "Algorithmica",
		Authors:    []string{"Zeta Avarikioti", "Ioannis Z Emiris", "Loukas Kavouras", "Ioannis Psarros"},
		Url:        "https://epubs.siam.org/doi/pdf/10.1137/1.9781611974782.2",
		Tags:       []Tag{},
	},
	{
		Handle:         "approximate-near-neighbors-in-high-dimension",
		Name:           "Practical linear-space Approximate Near Neighbors in high dimension",
		Conference:     "ArXiv",
		ConferenceYear: 2016,
		Authors:        []string{"Georgia Avarikioti", "Ioannis Z Emiris", "Ioannis Psarros", "Georgios Samaras"},
		Url:            "https://arxiv.org/pdf/1612.07405.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "game-theoretic-analysis-of-off-chain-protocols",
		Name:           "Towards a game-theoretic security analysis of off-chain protocols",
		Conference:     "Computer Security Foundations Symposium–CSF",
		ConferenceYear: 2023,
		Authors:        []string{"Sophie Rain", "Georgia Avarikioti", "Laura Kovács", "Matteo Maffei"},
		Url:            "https://arxiv.org/pdf/2109.07429.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:     "suborn-channels",
		Name:       "Suborn Channels: Incentives Against Timelock Bribes",
		Conference: "Financial Cryptography and Data Security",
		Authors:    []string{"Zeta Avarikioti", "Orfeas Stefanos Thyfronitis Litos"},
		Url:        "https://eprint.iacr.org/2022/814.pdf",
		Tags:       []Tag{LIGHTNING_NETWORK, BITCOIN, PAYMENT_CHANNELS},
	},
	{
		Handle:         "wiser",
		Name:           "Wiser: Increasing Throughput in Payment Channel Networks with Transaction Aggregation",
		Conference:     "Conference on Advances in Financial Technologies–AFT",
		ConferenceYear: 2022,
		Authors:        []string{"Samarth Tiwari", "Michelle Yeo", "Zeta Avarikioti", "Iosif Salem", "Krzysztof Pietrzak", "Stefan Schmid"},
		Url:            "https://arxiv.org/pdf/2205.11597.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, PRIVACY},
	},
	{
		Handle:         "lightning-ceration-games",
		Name:           "Lightning Creation Games",
		Conference:     "International Conference on Distributed Computing Systems–ICDCS",
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Tomasz Lizurej", "Tomasz Michalak", "Michelle Yeo"},
		Url:            "https://arxiv.org/pdf/2306.16006.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
	},
	{
		Handle:         "pos-sidechains",
		Name:           "Proof-of-Stake Sidechains",
		Conference:     "Symposium on Security and Privacy–S&P",
		ConferenceYear: 2019,
		Authors:        []string{"Peter Gaži", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2018/1239.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, INTEROPERABILITY},
	},
	{
		Handle:         "sok-distributed-ledger-communication",
		Name:           "SoK: Communication across distributed ledgers",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2021,
		Authors:        []string{"Alexei Zamyatin", "Mustafa Al-Bassam", "Dionysis Zindros", "Eleftherios Kokoris-Kogias", "Pedro Moreno-Sanchez", "Aggelos Kiayias", "William J Knottenbelt"},
		Url:            "https://eprint.iacr.org/2019/1128.pdf",
		Tags:           []Tag{INTEROPERABILITY},
	},
	{
		Handle:         "proof-of-burn",
		Name:           "Proof-of-Burn",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2020,
		Authors:        []string{"Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2019/1096.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "pow-sidechains",
		Name:           "Proof-of-Work Sidechains",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2019,
		Authors:        []string{"Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2018/1048.pdf",
		Tags:           []Tag{PROOF_OF_WORK, INTEROPERABILITY},
	},
	{
		Handle:         "trust-is-risk",
		Name:           "Trust is Risk: A Decentralized Financial Trust Platform",
		Conference:     "Financial Cryptography and Data Security",
		ConferenceYear: 2017,
		Authors:        []string{"Orfeas Stefanos Thyfronitis Litos", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2017/156.pdf",
		Tags:           []Tag{BITCOIN},
	},
	{
		Handle:         "updatable-blockchains",
		Name:           "Updatable Blockchains",
		Conference:     "European Symposium on Research in Computer Security–ESORICS",
		ConferenceYear: 2020,
		Authors:        []string{"Michele Ciampi", "Nikos Karayannidis", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/887.pdf",
		Tags:           []Tag{},
	},
	{
		Handle:         "cryptocurrency-egalitarianism",
		Name:           "Cryptocurrency Egalitarianism: A Quantitative Approach",
		Conference:     "International Conference on Blockchain Economics, Security and Protocols–Tokenomics",
		ConferenceYear: 2019,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Christos Nasikas", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1907.02434",
		Tags:           []Tag{PROOF_OF_WORK, PROOF_OF_STAKE},
	},
	{
		Handle:         "superblock-compact-storage-for-nipopows",
		Name:           "Compact storage of superblocks for NiPoPoW applications",
		Conference:     "Mathematical Research for Blockchain Economy–MARBLE",
		ConferenceYear: 2019,
		Authors:        []string{"Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2019/1444.pdf",
		Tags:           []Tag{PROOF_OF_WORK, INTEROPERABILITY},
	},
	{
		Handle:         "gas-efficient-superlight-client",
		Name:           "A Gas-Efficient Superlight Bitcoin Client in Solidity",
		Conference:     "Conference on Advances in Financial Technologies–ACM AFT",
		ConferenceYear: 2020,
		Authors:        []string{"Stelios Daveas", "Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/927.pdf",
		Tags:           []Tag{PROOF_OF_WORK, BITCOIN, SMART_CONTRACTS},
	},
	{
		Handle:         "logspace-mining",
		Name:           "Mining in Logarithmic Space",
		Conference:     "Conference on Computer and Communications Security–ACM SIGSAC",
		ConferenceYear: 2021,
		Authors:        []string{"Aggelos Kiayias", "Nikos Leonardos", "Dionysis Zindros"},
		Url:            "https://dl.acm.org/doi/pdf/10.1145/3460120.3484784",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
	},
	{
		Handle:         "ddh-ring-signatures",
		Name:           "Short Accountable Ring Signatures Based on DDH",
		Conference:     "European Symposium on Research in Computer Security–ESORICS",
		ConferenceYear: 2015,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth", "Christophe Petit"},
		Url:            "https://eprint.iacr.org/2015/643.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES},
	},
	{
		Handle:         "beleniosrf",
		Name:           "BeleniosRF: A Non-Interactive Receipt-Free Electronic Voting Scheme",
		Conference:     "Conference on Computer and Communications Security–ACM SIGSAC",
		ConferenceYear: 2016,
		Authors:        []string{"Pyrros Chaidos", "Véronique Cortier", "Georg Fuchsbauer", "David Galindo"},
		Url:            "https://eprint.iacr.org/2015/629.pdf",
		Tags:           []Tag{VOTING},
	},
	{
		Handle:         "arithmetization-oriented-hash-functions",
		Name:           "New Design Techniques for Efficient Arithmetization-Oriented Hash Functions:Anemoi Permutations and Jive Compression Mode",
		Conference:     "Annual International Cryptology Conference",
		ConferenceYear: 2023,
		Authors:        []string{"Clémence Bouvier1", "Pierre Briaud", "Pyrros Chaidos", "Léo Perrin", "Robin Salen", "Vesselin Velichkov", "Danny Willems"},
		Url:            "https://eprint.iacr.org/2022/840.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
	},
	{
		Handle:         "designated-verifier-nizkp",
		Name:           "Efficient Designated-Verifier Non-interactive Zero-Knowledge Proofs of Knowledge",
		Conference:     "Advances in Cryptology–EUROCRYPT",
		ConferenceYear: 2018,
		Authors:        []string{"Pyrros Chaidos", "Geoffroy Couteau"},
		Url:            "https://eprint.iacr.org/2017/1029.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
	},
	{
		Handle:         "non-interactive-sigmas-without-ro",
		Name:           "Making Sigma-protocols Non-interactive without Random Oracles",
		Conference:     "IACR International Workshop on Public Key Cryptography",
		ConferenceYear: 2015,
		Authors:        []string{"Pyrros Chaidos", "Jens Groth"},
		Url:            "https://www.iacr.org/archive/pkc2015/90200192/90200192.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, VOTING},
	},
	{
		Handle:         "efficient-zkp-systems",
		Name:           "Efficient Zero-Knowledge Proof Systems",
		Conference:     "International School on Foundations of Security Analysis and Design",
		ConferenceYear: 2015,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Jens Groth"},
		Url:            "https://jbootle.github.io/Misc/fosad2015.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, COMMITMENTS},
	},
	{
		Handle:         "mithril",
		Name:           "Mithril: Stake-based Threshold Multisignatures",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2021,
		Authors:        []string{"Pyrros Chaidos", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2021/916.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES, UC},
	},
	{
		Handle:         "fully-dynamic-group-signatures",
		Name:           "Foundations of Fully Dynamic Group Signatures",
		Conference:     "Applied Cryptography and Network Security",
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth"},
		Url:            "https://eprint.iacr.org/2016/368.pdf",
		Tags:           []Tag{SIGNATURES},
	},
	{
		Handle:         "divertibility-to-bling-ballot-copying-in-helios",
		Name:           "Applying Divertibility to Blind Ballot Copying in the Helios Internet Voting System",
		Conference:     "European Symposium on Research in Computer Security–ESORICS",
		ConferenceYear: 2012,
		Authors:        []string{"Yvo Desmedt", "Pyrros Chaidos"},
		Url:            "http://www0.cs.ucl.ac.uk/staff/P.Chaidos/helios-esorics-cr.pdf",
		Tags:           []Tag{VOTING, PRIVACY},
	},
	{
		Handle:         "pow-checkpointing",
		Name:           "Securing Proof-of-Work Ledgers via Checkpointing",
		Conference:     "IEEE International Conference on Blockchain and Cryptocurrency",
		ConferenceYear: 2021,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2020/173.pdf",
		Tags:           []Tag{PROOF_OF_WORK},
	},
	{
		Handle:         "sok-decentralization",
		Name:           "SoK: A Stratified Approach to Blockchain Decentralization",
		Conference:     "Cryptology ePrint Archive",
		ConferenceYear: 2022,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Christina Ovezik"},
		Url:            "https://arxiv.org/pdf/2211.01291.pdf",
		Tags:           []Tag{DECENTRALIZATION},
	},
	{
		Handle:         "pos-account-management",
		Name:           "Account Management in Proof of Stake Ledgers",
		Conference:     "Security and Cryptography for Networks–SCN",
		ConferenceYear: 2020,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2020/525.pdf",
		Tags:           []Tag{PROOF_OF_STAKE},
	},
	{
		Handle:         "puff-of-steem",
		Name:           "A Puff of Steem: Security Analysis of Decentralized Content Curation",
		Conference:     "International Conference on Blockchain Economics, Security and Protocols–Tokenomics",
		ConferenceYear: 2019,
		Authors:        []string{"Aggelos Kiayias", "Benjamin Livshits", "Andrés Monteoliva Mosteiro", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://www.pure.ed.ac.uk/ws/portalfiles/portal/129969711/A_Puff_of_Steem_KIAYIAS_DOA13012020_VOR_CC_BY.pdf",
		Tags:           []Tag{DECENTRALIZATION},
	},
}
