package main

type Tag string
type ConferenceAbbreviation string

const (
	PROOF_OF_STAKE    Tag = "proof-of-stake"
	PROOF_OF_WORK     Tag = "proof-of-work"
	LIQUID_STAKING    Tag = "liquid-staking"
	LIGHT_CLIENTS     Tag = "light-clients"
	INTEROPERABILITY  Tag = "interoperability"
	WALLETS           Tag = "wallets"
	PAYMENT_CHANNELS  Tag = "payment-channels"
	ZERO_KNOWLEDGE    Tag = "zero-knowledge"
	SIGNATURES        Tag = "signatures"
	LIGHTNING_NETWORK Tag = "lightning-network"
	SMART_CONTRACTS   Tag = "smart-contracts"
	PVSS              Tag = "pvss"
	RANDOMNESS        Tag = "randomness"
	CONSENSUS         Tag = "consensus"
	// IDENTIFICATION     Tag = "identification"
	MPC                Tag = "mpc"
	PRIVACY            Tag = "privacy"
	FAIRNESS           Tag = "fairness"
	FRONT_RUNNING      Tag = "front-running"
	TIMELOCK           Tag = "timelock"
	UC                 Tag = "universal-composability"
	DEFI               Tag = "defi"
	COMMITMENTS        Tag = "commitments"
	OBLIVIOUS_TRANSFER Tag = "oblivious-transfer"
	// ANONYMITY          Tag = "anonymity"
	MEV  Tag = "mev"
	YOSO Tag = "yoso"
	// ROM                Tag = "random-oracle"
	HOMOMORPHISM       Tag = "homomorphism"
	BITCOIN            Tag = "bitcoin"
	VOTING             Tag = "voting"
	SHARDING           Tag = "sharding"
	VDF                Tag = "verifiable-delay-functions"
	WITNESS_ENCRYPTION Tag = "witness-encryption"
	DECENTRALIZATION   Tag = "decentralization"
	// TIMELINESS         Tag = "timeliness"
	// SUPERSAFETY        Tag = "supersafety"
)

var TagToColor = map[Tag]string{
	PROOF_OF_STAKE:    "#e4cbf4",
	PROOF_OF_WORK:     "#ffc0c0",
	LIQUID_STAKING:    "#e6e6fa",
	LIGHT_CLIENTS:     "#fff3b0",
	INTEROPERABILITY:  "#a5d0ec",
	WALLETS:           "#e1ddad",
	PAYMENT_CHANNELS:  "#c5e2b5",
	ZERO_KNOWLEDGE:    "#e0b5e9",
	SIGNATURES:        "#fae2d9",
	LIGHTNING_NETWORK: "#d4e2d4",
	SMART_CONTRACTS:   "#f9e6fa",
	PVSS:              "#d9e4f5",
	RANDOMNESS:        "#d1f0fc",
	CONSENSUS:         "#e8d4b3",
	// IDENTIFICATION:     "#f6f0c4",
	MPC:                "#e5dcca",
	PRIVACY:            "#abc4c7",
	FAIRNESS:           "#d0f5d0",
	FRONT_RUNNING:      "#ffe4e9",
	TIMELOCK:           "#b3e6ff",
	UC:                 "#ffd9cc",
	DEFI:               "#e8ccf5",
	COMMITMENTS:        "#ffead4",
	OBLIVIOUS_TRANSFER: "#a8e8e8",
	// ANONYMITY:          "#c7d2d9",
	MEV:  "#f3b0e0",
	YOSO: "#ffd1b3",
	// ROM:                "#8cd1a4",
	HOMOMORPHISM:       "#e6a1a1",
	BITCOIN:            "#ffb732",
	VOTING:             "#d4b39e",
	SHARDING:           "#b0a8f5",
	VDF:                "#c2c2d1",
	WITNESS_ENCRYPTION: "#ffd4e6",
	DECENTRALIZATION:   "#f0deba",
	// TIMELINESS:         "#fabf8b",
	// SUPERSAFETY:        "#1fea33",
}

const (
	FC           ConferenceAbbreviation = "FC"
	FCWTS        ConferenceAbbreviation = "FCWTS"
	AFT          ConferenceAbbreviation = "AFT"
	CRYPTO       ConferenceAbbreviation = "CRYPTO"
	EUROCRYPT    ConferenceAbbreviation = "EUROCRYPT"
	ACNS         ConferenceAbbreviation = "ACNS"
	CSF          ConferenceAbbreviation = "CSF"
	PKC          ConferenceAbbreviation = "PKC"
	CCS          ConferenceAbbreviation = "CCS"
	ASIACRYPT    ConferenceAbbreviation = "ASIACRYPT"
	IJCSIT       ConferenceAbbreviation = "IJCSIT"
	IJCSE        ConferenceAbbreviation = "IJCSE"
	REVISTA      ConferenceAbbreviation = "Revista Telecommun"
	CANS         ConferenceAbbreviation = "CANS"
	EPRINT       ConferenceAbbreviation = "ePrint"
	PROVSEC      ConferenceAbbreviation = "PROVSEC"
	TIFS         ConferenceAbbreviation = "TIFS"
	ICITS        ConferenceAbbreviation = "ICITS"
	CTRSA        ConferenceAbbreviation = "CTRSA"
	ABEAT        ConferenceAbbreviation = "ABEAT"
	CRYBLOCK     ConferenceAbbreviation = "CRYBLOCK"
	ICOFCS       ConferenceAbbreviation = "ICOFCS"
	IEICET       ConferenceAbbreviation = "IEICET"
	DEC          ConferenceAbbreviation = "DEC"
	ACISP        ConferenceAbbreviation = "ACISP"
	ISTT         ConferenceAbbreviation = "ISTT"
	IWT          ConferenceAbbreviation = "IWT"
	ITASEC       ConferenceAbbreviation = "ITASEC"
	SIROCCO      ConferenceAbbreviation = "SIROCCO"
	ARXIV        ConferenceAbbreviation = "arXiv"
	ESORICS      ConferenceAbbreviation = "ESORICS"
	ISAAC        ConferenceAbbreviation = "ISAAC"
	ALGORITHMICA ConferenceAbbreviation = "ALGORITHMICA"
	DPMCBT       ConferenceAbbreviation = "DPMCBT"
	ICDCS        ConferenceAbbreviation = "ICDCS"
	SP           ConferenceAbbreviation = "S&P"
	TOKENOMICS   ConferenceAbbreviation = "TOKENOMICS"
	MARBLE       ConferenceAbbreviation = "MARBLE"
	SIGSAC       ConferenceAbbreviation = "SIGSAC"
	ICBC         ConferenceAbbreviation = "ICBC"
	SCN          ConferenceAbbreviation = "SCN"
	SRDS         ConferenceAbbreviation = "SRDS"
	MIDDLEWARE   ConferenceAbbreviation = "MIDDLEWARE"
	SSS          ConferenceAbbreviation = "SSS"
	AAAI         ConferenceAbbreviation = "AAAI"
	USENIX       ConferenceAbbreviation = "USENIX"
	FOSAD        ConferenceAbbreviation = "FOSAD"
	AUCS         ConferenceAbbreviation = "AUCS"
	SBSEG        ConferenceAbbreviation = "SBSEG"
)

var ConferenceAbbreviationToName = map[ConferenceAbbreviation]string{
	FC:           "Financial Cryptography and Data Security",
	FCWTS:        "Financial Cryptography and Data Security, Workshop in Trusted Smart Contracts",
	AFT:          "ACM Advances in Financial Technologies",
	CRYPTO:       "International Cryptology Conference–CRYPTO",
	EUROCRYPT:    "International Conference on the Theory and Applications of Cryptographic Techniques–EUROCRYPT",
	ACNS:         "International Conference on Applied Cryptography and Network Security",
	CSF:          "IEEE Computer Security Foundations Symposium",
	PKC:          "Public-Key Cryptography",
	CCS:          "ACM Conference on Computer and Communications Security",
	ASIACRYPT:    "International Conference on the Theory and Application of Cryptology and Information Security–ASIACRYPT",
	IJCSIT:       "International Journal of Computer Science & Information Technology–IJCSIT",
	IJCSE:        "International Journal of Computer Science and Engineering–IJCSE",
	REVISTA:      "Revista Telecommun",
	CANS:         "International Conference on Cryptology And Network Security–CANS",
	EPRINT:       "Cryptology ePrint Archive",
	PROVSEC:      "International Conference on Provable Security",
	TIFS:         "IEEE Transactions on Information Forensics and Security",
	ICITS:        "International Conference on Information Technology & Systems",
	CTRSA:        "The Cryptographers' Track at RSA Conference",
	ABEAT:        "Brazilian Association of High Technology Experts",
	CRYBLOCK:     "Workshop on Cryptocurrencies and Blockchains",
	DEC:          "ACM Data Economy Workshop",
	ACISP:        "Australasian Conference on Information Security and Privacy",
	IWT:          "International Workshop on Trust",
	ITASEC:       "Italian Conference on Cybersecurity",
	SIROCCO:      "International Colloquium on Structural Information and Communication Complexity",
	ARXIV:        "arXiv",
	ESORICS:      "European Symposium on Research in Computer Security",
	ISAAC:        "International Symposium on Algorithms and Computation",
	ALGORITHMICA: "Algorithmica",
	DPMCBT:       "Data Privacy Management, Cryptocurrencies and Blockchain Technology",
	ICDCS:        "International Conference on Distributed Computing Systems",
	SP:           "IEEE Symposium on Security and Privacy",
	TOKENOMICS:   "International Conference on Blockchain Economics, Security and Protocols",
	MARBLE:       "International Conference on Mathematical Research for Blockchain Economy",
	SIGSAC:       "ACM Special Interest Group on Security, Audit and Control",
	ICBC:         "IEEE International Conference on Blockchain and Cryptocurrency",
	SCN:          "International Conference on Security and Communication Networks",
	SRDS:         "IEEE Symposium on Reliable Distributed Systems",
	MIDDLEWARE:   "International Middleware Conference",
	SSS:          "International Symposium on Stabilization, Safety, and Security of Distributed Systems",
	AAAI:         "Association for the Advancement of Artificial Intelligence",
	USENIX:       "USENIX Security Symposium",
	FOSAD:        "International School on Foundations of Security Analysis and Design",
	AUCS:         "Aarhus University, Computer Science Department, Dissertation",
	SBSEG:        "Brazilian Symposium on Information and Computer System Security",
}

var ResearchPapers []ResearchPaper = []ResearchPaper{
	{
		Handle:         "timeliness",
		Name:           "On-Chain Timestamps Are Accurate",
		Conference:     FC,
		ConferenceYear: 2024,
		Authors:        []string{"Apostolos Tzinas", "Srivatsan Sridhar", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2023/1648.pdf",
		Tags:           []Tag{}, // TIMELINESS, SUPERSAFETY
		Citations:      1,
	},
	{
		Handle:         "liquid-staking",
		Name:           "The Principal–Agent Problem in Liquid Staking",
		Conference:     FCWTS,
		ConferenceYear: 2023,
		Authors:        []string{"Apostolos Tzinas", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2023/605.pdf",
		Tags:           []Tag{LIQUID_STAKING},
		Citations:      5,
	},
	{
		Handle:         "blink",
		Name:           "Blink: An Optimal Proof of Proof-of-Work",
		Conference:     FC,
		ConferenceYear: 2024,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Matteo Maffei", "Giulia Scaffino", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2024/692.pdf",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      4,
	},
	{
		Handle:         "better-pow-fork-rule",
		Name:           "A Better Proof-of-Work Fork Choice Rule",
		Conference:     EPRINT,
		ConferenceYear: 2024,
		Authors:        []string{"Karl Kreder", "Shreekara Shastry", "Apostolos Tzinas", "Sriram Vishwanath", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2024/200.pdf",
		Tags:           []Tag{PROOF_OF_WORK, CONSENSUS},
		Citations:      0,
	},
	{
		Handle:         "pod",
		Name:           "Pod: An Optimal-Latency, Censorship-Free, and Accountable Generalized Consensus Layer",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Orestis Alpos", "Bernardo David", "Jakov Mitrovski", "Odysseas Sofikitis", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/2501.14931",
		Tags:           []Tag{CONSENSUS, DECENTRALIZATION},
		Citations:      2,
	},
	{
		Handle:         "consensus-protocols-overview",
		Name:           "An overview of the efficiency and censorship-resistance guarantees of widely-used consensus protocols",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Orestis Alpos", "Bernardo David", "Nikolaos Kamarinakis", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/2504.03588",
		Tags:           []Tag{CONSENSUS, DECENTRALIZATION, FAIRNESS},
		Citations:      0,
	},
}


var OldResearchPapers []ResearchPaper = []ResearchPaper{
	{
		Handle:         "popos",
		Name:           "Proofs of Proof-of-Stake with Sublinear Complexity",
		Conference:     AFT,
		ConferenceYear: 2023,
		Authors:        []string{"Shresth Agrawal", "Joachim Neu", "Ertem Nusret Tas", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/2209.08673.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      8,
	},
	{
		Handle:         "nipopow",
		Name:           "Non-Interactive Proofs of Proof-of-Work",
		Conference:     FC,
		ConferenceYear: 2020,
		Authors:        []string{"Aggelos Kiayias", "Andrew Miller", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2017/963.pdf",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      175,
	},
	{
		Handle:         "ouroboros",
		Name:           "Ouroboros: A provably secure proof-of-stake blockchain protocol",
		Conference:     CRYPTO,
		ConferenceYear: 2017,
		Authors:        []string{"Aggelos Kiayias", "Alexander Russell", "Bernardo David", "Roman Oliynykov"},
		Url:            "https://eprint.iacr.org/2016/889.pdf",
		Tags:           []Tag{PROOF_OF_STAKE},
		Citations:      1974,
	},
	{
		Handle:         "hardware-wallets",
		Name:           "A formal treatment of hardware wallets",
		Conference:     FC,
		ConferenceYear: 2019,
		Authors:        []string{"Myrto Arapinis", "Andriana Gkaniatsou", "Dimitris Karakostas", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2019/034.pdf",
		Tags:           []Tag{WALLETS},
		Citations:      38,
	},
	{
		Handle:         "brick",
		Name:           "Brick: Asynchronous Incentive-Compatible Payment Channels",
		Conference:     FC,
		ConferenceYear: 2021,
		Authors:        []string{"Zeta Avarikioti", "Eleftherios Kokoris-Kogias", "Roger Wattenhofer", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1905.11360.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      70,
	},
	{
		Handle:         "zk-arguments",
		Name:           "Efficient Zero-Knowledge Arguments for Arithmetic Circuits in the Discrete Log Setting",
		Conference:     EUROCRYPT,
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Jens Groth", "Christophe Petit"},
		Url:            "https://eprint.iacr.org/2016/263.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
		Citations:      412,
	},
	{
		Handle:         "dynamic-group-signatures",
		Name:           "Foundations of Fully Dynamic Group Signatures",
		Conference:     ACNS,
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth"},
		Url:            "https://eprint.iacr.org/2016/368.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      129,
	},
	{
		Handle:         "lightning-network-security",
		Name:           "A Composable Security Treatment of the Lightning Network",
		Conference:     CSF,
		ConferenceYear: 2020,
		Authors:        []string{"Aggelos Kiayias", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://eprint.iacr.org/2019/778.pdf",
		Tags:           []Tag{LIGHTNING_NETWORK},
		Citations:      54,
	},
	{
		Handle:         "ouroboros-praos",
		Name:           "Ouroboros Praos: An adaptively-secure, semi-synchronous proof-of-stake blockchain",
		Conference:     EUROCRYPT,
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Peter Gaži", "Aggelos Kiayias", "Alexander Russell"},
		Url:            "https://eprint.iacr.org/2017/573.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, CONSENSUS},
		Citations:      584,
	},
	{
		Handle:         "scape",
		Name:           "SCRAPE: Scalable randomness attested by public entities",
		Conference:     ACNS,
		ConferenceYear: 2017,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2017/216.pdf",
		Tags:           []Tag{PVSS, RANDOMNESS},
		Citations:      172,
	},
	{
		Handle:         "constant-sps",
		Name:           "Constant-size structure-preserving signatures: Generic constructions and simple assumptions",
		Conference:     ASIACRYPT,
		ConferenceYear: 2012,
		Authors:        []string{"Masayuki Abe", "Melissa Chase", "Bernardo David", "Markulf Kohlweiss", "Ryo Nishimaki", "Miyako Ohkubo"},
		Url:            "https://eprint.iacr.org/2012/285.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      137,
	},
	{
		Handle:         "tagged-ots",
		Name:           "Tagged one-time signatures: Tight security and optimal tag size",
		Conference:     PKC,
		ConferenceYear: 2013,
		Authors:        []string{"Masayuki Abe", "Bernardo David", "Markulf Kohlweiss", "Ryo Nishimaki", "Miyako Ohkubo"},
		Url:            "https://eprint.iacr.org/2015/311.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      96,
	},
	{
		Handle:         "internet-banking-attacks",
		Name:           "A Formal Classification of Internet Banking Attacks and Vulnerabilities",
		Conference:     IJCSIT,
		ConferenceYear: 2011,
		Authors:        []string{"Laerte Peotta", "Marcelo Holtz", "Bernardo David", "Flavio Deus", "RT de Sousa"},
		Url:            "https://airccse.org/journal/jcsit/0211ijcsit13.pdf",
		Tags:           []Tag{}, // IDENTIFICATION
		Citations:      83,
	},
	{
		Handle:         "albatross",
		Name:           "ALBATROSS: Publicly AttestabLe BATched Randomness Based On Secret Sharing",
		Conference:     ASIACRYPT,
		ConferenceYear: 2020,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2020/644.pdf",
		Tags:           []Tag{RANDOMNESS, PVSS},
		Citations:      66,
	},
	{
		Handle:         "p2dex",
		Name:           "P2DEX: privacy-preserving decentralized cryptocurrency exchange",
		Conference:     ACNS,
		ConferenceYear: 2021,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2021/283.pdf",
		Tags:           []Tag{MPC, PRIVACY, FAIRNESS, FRONT_RUNNING},
		Citations:      65,
	},
	{
		Handle:         "tardis",
		Name:           "TARDIS: a foundation of time-lock puzzles in UC",
		Conference:     EUROCRYPT,
		ConferenceYear: 2021,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley", "Jesper Buus Nielsen", "Sabine Oechsner"},
		Url:            "https://eprint.iacr.org/2020/537.pdf",
		Tags:           []Tag{TIMELOCK, UC},
		Citations:      51,
	},
	{
		Handle:         "uc-commitments",
		Name:           "Rate-1, linear time and additively homomorphic UC commitments",
		Conference:     CRYPTO,
		ConferenceYear: 2016,
		Authors:        []string{"Ignacio Cascudo", "Ivan Damgård", "Bernardo David", "Nico Döttling", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2016/137.pdf",
		Tags:           []Tag{COMMITMENTS, UC},
		Citations:      41,
	},
	{
		Handle:         "insured-mpc",
		Name:           "Insured MPC: Efficient secure computation with financial penalties",
		Conference:     FC,
		ConferenceYear: 2020,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2018/942.pdf",
		Tags:           []Tag{MPC, FAIRNESS, UC},
		Citations:      48,
	},
	{
		Handle:         "map-reduce-ids",
		Name:           "Building Scalable Distributed Intrusion Detection Systems Based on the MapReduce Framework",
		Conference:     REVISTA,
		ConferenceYear: 2011,
		Authors:        []string{"Marcelo D Holtz", "Bernardo David", "Rafael Timóteo de Sousa Júnior"},
		Url:            "https://www.academia.edu/download/61520800/Building_Scalable_Distributed_Intrusion_20191215-6958-g7aso0.pdf",
		Tags:           []Tag{},
		Citations:      38,
	},
	{
		Handle:         "vss-homomorphic-uc-commitments",
		Name:           "Compact VSS and efficient homomorphic UC commitments",
		Conference:     ASIACRYPT,
		ConferenceYear: 2014,
		Authors:        []string{"Ivan Damgård", "Bernardo David", "Irene Giacomelli", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2014/370.pdf",
		Tags:           []Tag{UC, COMMITMENTS, HOMOMORPHISM},
		Citations:      37,
	},
	{
		Handle:         "lpn-uc-transfer",
		Name:           "Universally composable oblivious transfer based on a variant of LPN",
		Conference:     CANS,
		ConferenceYear: 2014,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Anderson CA Nascimento"},
		Url:            "https://dowsley.net/pdf/CANS-DavDowNas14.pdf",
		Tags:           []Tag{UC, OBLIVIOUS_TRANSFER},
		Citations:      39,
	},
	{
		Handle:         "uc-rom-oblivious-transfer",
		Name:           "A Framework for Efficient Adaptively Secure Composable Oblivious Transfer in the ROM",
		Conference:     EPRINT,
		ConferenceYear: 2017,
		Authors:        []string{"Paulo SLM Barreto", "Bernardo David", "Rafael Dowsley", "Kirill Morozov", "Anderson CA Nascimento"},
		Url:            "https://eprint.iacr.org/2017/993.pdf",
		Tags:           []Tag{UC, OBLIVIOUS_TRANSFER}, // ROM
		Citations:      40,
	},
	{
		Handle:         "private-ml-classification",
		Name:           "Efficient unconditionally secure comparison and privacy preserving machine learning classification protocols",
		Conference:     PROVSEC,
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Raj Katti", "Anderson CA Nascimento"},
		Url:            "https://dowsley.net/pdf/PROVSEC-DDKN15.pdf",
		Tags:           []Tag{PRIVACY},
		Citations:      35,
	},
	{
		Handle:         "homomorphic-uc-commitments",
		Name:           "Additively Homomorphic UC commitments with Optimal Amortized Overhead",
		Conference:     PKC,
		ConferenceYear: 2015,
		Authors:        []string{"Ignacio Cascudo Pueyo", "Ivan Bjerre Damgård", "Bernardo Machado David", "Irene Giacomelli", "Jesper Buus Nielsen", "Roberto Trifiletti"},
		Url:            "https://eprint.iacr.org/2014/829.pdf",
		Tags:           []Tag{UC, COMMITMENTS},
		Citations:      33,
	},
	{
		Handle:         "craft",
		Name:           "CRAFT: Composable Randomness Beacons and Output-Independent Abort MPC From Time",
		Conference:     PKC,
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley", "Ravi Kishore", "Jesper Buus Nielsen", "Sabine Oechsner"},
		Url:            "https://eprint.iacr.org/2020/784.pdf",
		Tags:           []Tag{UC, TIMELOCK, VDF, RANDOMNESS},
		Citations:      34,
	},
	{
		Handle:         "front-running-sok",
		Name:           "SoK: Mitigation of front-running in decentralized finance",
		Conference:     FC,
		ConferenceYear: 2022,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen", "Lorenzo Gentile"},
		Url:            "https://eprint.iacr.org/2021/1628.pdf",
		Tags:           []Tag{DEFI, FRONT_RUNNING, MEV},
		Citations:      34,
	},
	{
		Handle:         "anonymous-timelock",
		Name:           "Encryption to the future: a paradigm for sending secret messages to future (anonymous) committees",
		Conference:     ASIACRYPT,
		ConferenceYear: 2022,
		Authors:        []string{"Matteo Campanelli", "Bernardo David", "Hamidreza Khoshakhlagh", "Anders Konring", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2021/1423.pdf",
		Tags:           []Tag{TIMELOCK, WITNESS_ENCRYPTION},
		Citations:      35,
	},
	{
		Handle:         "gearbox",
		Name:           "GearBox: An Efficient UC Sharded Ledger Leveraging the Safety-Liveness Dichotomy.",
		Conference:     CCS,
		ConferenceYear: 2022,
		Authors:        []string{"Bernardo David", "Bernardo Magri", "Christian Matt", "Jesper Buus Nielsen", "Daniel Tschudi"},
		Url:            "https://eprint.iacr.org/2021/211.pdf",
		Tags:           []Tag{UC, SHARDING},
		Citations:      34,
	},
	{
		Handle:         "kaleidoscope",
		Name:           "Kaleidoscope: An efficient poker protocol with payment distribution and penalty enforcement",
		Conference:     FC,
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2017/899.pdf",
		Tags:           []Tag{MPC},
		Citations:      23,
	},
	{
		Handle:         "uc-private-linear-algebra",
		Name:           "Unconditionally secure, universally composable privacy preserving linear algebra",
		Conference:     TIFS,
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Jeroen van de Graaf", "Davidson Marques", "Anderson CA Nascimento", "Adriana CB Pinto"},
		Url:            "https://dowsley.net/pdf/IEEEIFS-DDGM+16.pdf",
		Tags:           []Tag{UC, PRIVACY},
		Citations:      22,
	},
	{
		Handle:         "yolo-yoso",
		Name:           "YOLO YOSO: Fast and simple encryption and secret sharing in the YOSO model",
		Conference:     ASIACRYPT,
		ConferenceYear: 2022,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David", "Lydia Garms", "Anders Konring"},
		Url:            "https://eprint.iacr.org/2022/242.pdf",
		Tags:           []Tag{PVSS, YOSO}, // ANONYMITY
		Citations:      22,
	},
	{
		Handle:         "uc-oblivious-transfer",
		Name:           "Universally composable oblivious transfer from lossy encryption and the McEliece assumptions",
		Conference:     ICITS,
		ConferenceYear: 2012,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Jörn Müller-Quade"},
		Url:            "https://link.springer.com/chapter/10.1007/978-3-642-32284-6_5",
		Tags:           []Tag{UC, OBLIVIOUS_TRANSFER},
		Citations:      16,
	},
	{
		Handle:         "honeypot-blind-malicious-activity-detection",
		Name:           "Blind automatic malicious activity detection in honeypot data",
		Conference:     ICOFCS,
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "JPCL da Costa", "Anderson CA Nascimento", "Dino Amaral", "MD Holtz", "RT de Sousa Jr"},
		Url:            "https://lasp.unb.br/wp-content/uploads/papers/ICoFCS2011-PP16.pdf",
		Tags:           []Tag{},
		Citations:      15,
	},
	{
		Handle:         "eagle",
		Name:           "Eagle: Efficient privacy preserving smart contracts",
		Conference:     FC,
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2022/1435.pdf",
		Tags:           []Tag{SMART_CONTRACTS, MPC},
		Citations:      16,
	},
	{
		Handle:         "uc-homomorphic-commitments",
		Name:           "Efficient UC Commitment Extension with Homomorphism for Free (and Applications)",
		Conference:     ASIACRYPT,
		ConferenceYear: 2019,
		Authors:        []string{"Ignacio Cascudo", "Ivan Damgård", "Bernardo David", "Nico Döttling", "Rafael Dowsley", "Irene Giacomelli"},
		Url:            "https://eprint.iacr.org/2018/983.pdf",
		Tags:           []Tag{UC, HOMOMORPHISM},
		Citations:      13,
	},
	{
		Handle:         "royale",
		Name:           "ROYALE: a framework for universally composable card games with financial rewards and penalties enforcement",
		Conference:     FC,
		ConferenceYear: 2019,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2018/157.pdf",
		Tags:           []Tag{UC, FAIRNESS},
		Citations:      14,
	},
	{
		Handle:         "mars",
		Name:           "MARS: Monetized Ad-hoc Routing System (A Position Paper)",
		Conference:     CRYBLOCK,
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://dl.acm.org/doi/10.1145/3211933.3211948",
		Tags:           []Tag{},
		Citations:      12,
	},
	{
		Handle:         "improved-honeypot-blind-malicious-activity-detection",
		Name:           "Improved blind automatic malicious activity detection in honeypot data",
		Conference:     ICOFCS,
		ConferenceYear: 2012,
		Authors:        []string{"JPCL da Costa", "Edison Pignaton de Freitas", "Bernardo Machado David", "AM Rubio Serrano", "Dino Amaral", "RT Sousa Júnior"},
		Url:            "http://www.icofcs.org/2012/ICoFCS2012_08.pdf",
		Tags:           []Tag{},
		Citations:      12,
	},
	{
		Handle:         "fast",
		Name:           "FAST: Fair Auctions via Secret Transactions",
		Conference:     ACNS,
		ConferenceYear: 2022,
		Authors:        []string{"Bernardo David", "Lorenzo Gentile", "Mohsen Pourpouneh"},
		Url:            "https://eprint.iacr.org/2021/264.pdf",
		Tags:           []Tag{FAIRNESS, PRIVACY},
		Citations:      13,
	},
	{
		Handle:         "uc-private-proximity-testing",
		Name:           "Universally composable private proximity testing",
		Conference:     PROVSEC,
		ConferenceYear: 2011,
		Authors:        []string{"Rafael Tonicelli", "Bernardo Machado David", "Vinícius de Morais Alves"},
		Url:            "https://link.springer.com/chapter/10.1007/978-3-642-24316-5_16",
		Tags:           []Tag{UC, PRIVACY},
		Citations:      11,
	},
	{
		Handle:         "secure-sso",
		Name:           "A framework for secure single sign-on",
		Conference:     EPRINT,
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Rafael Tonicelli"},
		Url:            "https://eprint.iacr.org/2011/246.pdf",
		Tags:           []Tag{},
		Citations:      9,
	},
	{
		Handle:         "mt-random",
		Name:           "Mt. Random: Multi-tiered randomness beacons",
		Conference:     ACNS,
		ConferenceYear: 2023,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David", "Omer Shlomovits", "Denis Varlakov"},
		Url:            "https://eprint.iacr.org/2021/1096.pdf",
		Tags:           []Tag{RANDOMNESS, PVSS},
		Citations:      9,
	},
	{
		Handle:         "oblivious-transfer-from-mceliece",
		Name:           "Efficient fully simulatable oblivious transfer from the McEliece assumptions",
		Conference:     IEICET,
		ConferenceYear: 2012,
		Authors:        []string{"Bernardo Machado David", "Anderson CA Nascimento", "Rafael T de Sousa"},
		Url:            "https://ieeexplore.ieee.org/document/6089575",
		Tags:           []Tag{},
		Citations:      7,
	},
	{
		Handle:         "papr",
		Name:           "PAPR: Publicly auditable privacy revocation for anonymous credentials",
		Conference:     CTRSA,
		ConferenceYear: 2023,
		Authors:        []string{"Joakim Brorsson", "Bernardo David", "Lorenzo Gentile", "Elena Pagnin", "Paul Stankovski Wagner"},
		Url:            "https://eprint.iacr.org/2023/137.pdf",
		Tags:           []Tag{PRIVACY},
		Citations:      10,
	},
	{
		Handle:         "generalizing-mpc",
		Name:           "Generalizing efficient multiparty computation",
		Conference:     ICITS,
		ConferenceYear: 2015,
		Authors:        []string{"Bernardo M David", "Ryo Nishimaki", "Samuel Ranellucci", "Alain Tapp"},
		Url:            "https://eprint.iacr.org/2015/135.pdf",
		Tags:           []Tag{MPC, OBLIVIOUS_TRANSFER, UC},
		Citations:      6,
	},
	{
		Handle:         "pca-based-malicious-activity-detection",
		Name:           "A Parallel Approach to PCA Based Malicious Activity Detection in Distributed Honeypot Data",
		Conference:     ABEAT,
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo Machado David", "João Paulo Carvalho Lustosa da Costa", "Anderson Clayton Alves Nascimento", "Marcelo Dias Holtz", "Dino Macedo Amaral", "Rafael Timóteo de Sousa Júnior"},
		Url:            "http://www.realp.unb.br/jspui/bitstream/10482/10985/1/ARTIGO_ParallelApproachPCA.pdf",
		Tags:           []Tag{},
		Citations:      7,
	},
	{
		Handle:         "uc-verifiability-without-adaptivity-or-zk",
		Name:           "(Public) Verifiability for Composable Protocols Without Adaptivity or Zero-Knowledge",
		Conference:     PROVSEC,
		ConferenceYear: 2022,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2020/207.pdf",
		Tags:           []Tag{UC},
		Citations:      5,
	},
	{
		Handle:         "21",
		Name:           "21-bringing down the complexity: fast composable protocols for card games without secret state",
		Conference:     ACISP,
		ConferenceYear: 2018,
		Authors:        []string{"Bernardo David", "Rafael Dowsley", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2018/303.pdf",
		Tags:           []Tag{MPC, UC},
		Citations:      6,
	},
	{
		Handle:         "bayesian-trust-model-for-mac-in-802-15-4",
		Name:           "A Bayesian Trust Model for the MAC Layer in IEEE 802.15.4 Networks",
		Conference:     ISTT,
		ConferenceYear: 2010,
		Authors:        []string{"Bernardo Machado David", "Rafael Timoteo de Sousa Jr"},
		Url:            "http://www.inf.ufsc.br/~bosco.sobral/downloads/I2TS%202010%20CD%20Proceedings/www.i2ts.org/papers/full_english/78855_1.pdf",
		Tags:           []Tag{},
		Citations:      5,
	},
	{
		Handle:         "sok-privacy-in-finance",
		Name:           "SoK: Privacy-Enhancing Technologies in Finance",
		Conference:     AFT,
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "James Hsin-yu Chiang", "Bernardo David", "Tore Kasper Frederiksen"},
		Url:            "https://eprint.iacr.org/2023/122.pdf",
		Tags:           []Tag{DEFI, MPC, PRIVACY, ZERO_KNOWLEDGE},
		Citations:      9,
	},
	{
		Handle:         "trust-model-for-mac-in-lr-wpans",
		Name:           "A Context-Dependent Trust Model for the MAC Layer in LR-WPANs",
		Conference:     IJCSE,
		ConferenceYear: 2010,
		Authors:        []string{"Bernardo M David", "Beatriz Santana", "Laerte Peotta", "Marcelo D Holtz", "Rafael Timóteo de Sousa Jr"},
		Url:            "https://www.researchgate.net/profile/Rafael-De-Sousa-Junior/publication/50235175_A_Context-Dependent_Trust_Model_for_the_MAC_Layer_in_LR-WPANs_Bernardo_M_David_Beatriz_Santana_Laerte_Peotta_Marcelo_D_Holtz/links/549081910cf2d1800d866a6d/A-Context-Dependent-Trust-Model-for-the-MAC-Layer-in-LR-WPANs-Bernardo-M-David-Beatriz-Santana-Laerte-Peotta-Marcelo-D-Holtz.pdf",
		Tags:           []Tag{},
		Citations:      4,
	},
	{
		Handle:         "mpc-over-layered-graphs",
		Name:           "Perfect MPC over Layered Graphs",
		Conference:     CRYPTO,
		ConferenceYear: 2023,
		Authors:        []string{"Bernardo David", "Giovanni Deligios", "Aarushi Goel", "Yuval Ishai", "Anders Konring", "Eyal Kushilevitz", "Chen-Da Liu-Zhang", "Varun Narayanan"},
		Url:            "https://eprint.iacr.org/2023/330.pdf",
		Tags:           []Tag{MPC, YOSO},
		Citations:      6,
	},
	{
		Handle:         "uc-oblivious-transfer-from-cdh",
		Name:           "Efficient Composable Oblivious Transfer from CDH in the Global Random Oracle Model",
		Conference:     CANS,
		ConferenceYear: 2020,
		Authors:        []string{"Bernardo David", "Rafael Dowsley"},
		Url:            "https://eprint.iacr.org/2020/1291.pdf",
		Tags:           []Tag{OBLIVIOUS_TRANSFER, UC},
		Citations:      3,
	},
	{
		Handle:         "map-reduce-intrusion-detection-architecture",
		Name:           "An architecture for distributed Network Intrusion Detection Based on the Map-Reduce Framework",
		Conference:     IWT,
		ConferenceYear: 2011,
		Authors:        []string{"Marcelo D Holtz", "Bernardo M David", "Laerte Peotta", "RT de Sousa Jr"},
		Url:            "https://www.researchgate.net/publication/52011678_An_architecture_for_distributed_Network_Intrusion_Detection_Based_on_the_Map-Reduce_Framework",
		Tags:           []Tag{},
		Citations:      2,
	},
	{
		Handle:         "decentralized-info-market",
		Name:           "A Decentralized Information Marketplace Preserving Input and Output Privacy",
		Conference:     DEC,
		ConferenceYear: 2023,
		Authors:        []string{"Steven Golob", "Sikha Pentyala", "Rafael Dowsley", "Bernardo David", "Mario Larangeira", "Martine De Cock", "Anderson Nascimento"},
		Url:            "https://dl.acm.org/doi/pdf/10.1145/3600046.3600047",
		Tags:           []Tag{PRIVACY, MPC},
		Citations:      1,
	},
	{
		Handle:         "fairpos",
		Name:           "FairPoS: Input Fairness in Permissionless Consensus",
		Conference:     AFT,
		ConferenceYear: 2023,
		Authors:        []string{"James Hsin-yu Chiang", "Bernardo David", "Ittay Eyal", "Tiantian Gong"},
		Url:            "https://eprint.iacr.org/2022/1442.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, FRONT_RUNNING},
		Citations:      7,
	},
	{
		Handle:         "co-differential-privacy",
		Name:           "Correlated-Output Differential Privacy and Applications to Dark Pools",
		Conference:     EPRINT,
		ConferenceYear: 2023,
		Authors:        []string{"James Hsin-yu Chiang", "Bernardo David", "Mariana Gama", "Christian Janos Lebeda"},
		Url:            "https://eprint.iacr.org/2023/943.pdf",
		Tags:           []Tag{DEFI, MPC},
		Citations:      2,
	},
	{
		Handle:         "voting-diff-privacy",
		Name:           "Local Differential Privacy in Voting",
		Conference:     ITASEC,
		ConferenceYear: 2023,
		Authors:        []string{"Rosario Giustolisi", "Bernardo David", "Victor Mortensen", "Morten Pedersen"},
		Url:            "https://ceur-ws.org/Vol-3488/paper16.pdf",
		Tags:           []Tag{VOTING, PRIVACY},
		Citations:      0,
	},
	{
		Handle:         "updatable-private-blueprints",
		Name:           "Updatable Privacy-Preserving Blueprints",
		Conference:     EPRINT,
		ConferenceYear: 2023,
		Authors:        []string{"Bernardo David", "Felix Engelmann", "Tore Frederiksen", "Markulf Kohlweiss", "Elena Pagnin", "Mikhail Volkhov"},
		Url:            "https://eprint.iacr.org/2023/1787.pdf",
		Tags:           []Tag{PRIVACY, ZERO_KNOWLEDGE},
		Citations:      0,
	},
	{
		Handle:         "pvss-over-class-groups",
		Name:           "Publicly Verifiable Secret Sharing over Class Groups and Applications to DKG and YOSO",
		Conference:     EUROCRYPT,
		ConferenceYear: 2024,
		Authors:        []string{"Ignacio Cascudo", "Bernardo David"},
		Url:            "https://eprint.iacr.org/2023/1651.pdf",
		Tags:           []Tag{PVSS, MPC, YOSO},
		Citations:      3,
	},
	{
		Handle:         "cascade",
		Name:           "CaSCaDE: (Time-Based) Cryptography from Space Communications DElay",
		Conference:     EPRINT,
		ConferenceYear: 2023,
		Authors:        []string{"Carsten Baum", "Bernardo David", "Elena Pagnin", "Akira Takahashi"},
		Url:            "https://eprint.iacr.org/2023/405.pdf",
		Tags:           []Tag{TIMELOCK, VDF},
		Citations:      0,
	},
	{
		Handle:         "uc-homomorphic-commitments",
		Name:           "A Framework For Efficient Homomorphic Universally Composable Commitments",
		Conference:     AUCS,
		ConferenceYear: 2016,
		Authors:        []string{"Bernardo Machado David"},
		Url:            "https://pure.au.dk/ws/portalfiles/portal/114777545/Bernardo_Machado_Davids_thesis.pdf",
		Tags:           []Tag{UC, COMMITMENTS},
		Citations:      0,
	},
	{
		Handle:         "uc-committed-oblivious-transfer-with-trusted-initializer",
		Name:           "Universally Composable Committed Oblivious Transfer With A Trusted Initializer",
		Conference:     SBSEG,
		ConferenceYear: 2012,
		Authors:        []string{"Adriana CB Pinto", "Bernardo Machado David", "Jeroen van de Graaf", "Anderson CA Nascimento"},
		Url:            "https://sol.sbc.org.br/index.php/sbseg/article/download/20541/20368",
		Tags:           []Tag{OBLIVIOUS_TRANSFER, UC},
		Citations:      0,
	},
	{
		Handle:         "fully-simulatable-oblivious-transfer",
		Name:           "Obtaining Efficient Fully Simulatable Oblivious Transfer from General Assumptions",
		Conference:     SBSEG,
		ConferenceYear: 2011,
		Authors:        []string{"Bernardo M David", "Anderson CA Nascimento", "Rafael Tonicelli"},
		Url:            "https://sol.sbc.org.br/index.php/sbseg/article/download/20567/20394",
		Tags:           []Tag{OBLIVIOUS_TRANSFER},
		Citations:      0,
	},
	{
		Handle:         "cerberus-channels",
		Name:           "Cerberus Channels: Incentivizing Watchtowers for Bitcoin",
		Conference:     FC,
		ConferenceYear: 2020,
		Authors:        []string{"Zeta Avarikioti", "Orfeas Stefanos Thyfronitis Litos", "Roger Wattenhofer"},
		Url:            "https://eprint.iacr.org/2019/1092.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
		Citations:      62,
	},
	{
		Handle:         "divide-and-scale",
		Name:           "Divide & Scale: Formalization and Roadmap to Robust Sharding",
		Conference:     SIROCCO,
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Antoine Desjardins", "Lefteris Kokoris-Kogias", "Roger Wattenhofer"},
		Url:            "https://drive.google.com/file/d/1EKbY-8rCNj7zDTuVYcj5WAiFX2hYwqai/view",
		Tags:           []Tag{SHARDING},
		Citations:      47,
	},
	{
		Handle:         "secure-and-efficient-payment-channels",
		Name:           "Towards secure and efficient payment channels",
		Conference:     ARXIV,
		ConferenceYear: 2018,
		Authors:        []string{"Zeta Avarikioti", "Felix Laufenberg", "Jakub Sliwinski", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1811.12740.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
		Citations:      39,
	},
	{
		Handle:         "ride-the-lightning",
		Name:           "Ride the lightning: The game theory of payment channels",
		Conference:     FC,
		ConferenceYear: 2020,
		Authors:        []string{"Zeta Avarikioti", "Lioba Heimbach", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1912.04797.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      38,
	},
	{
		Handle:         "payment-network-with-fees",
		Name:           "Payment network design with fees",
		Conference:     ESORICS,
		ConferenceYear: 2018,
		Authors:        []string{"Zeta Avarikioti", "Gerrit Janssen", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1810.07585.pdf",
		Tags:           []Tag{}, //keywords:  blockchain, layer 2, channels, lightning protocol
		Citations:      32,
	},
	{
		Handle:         "darknet",
		Name:           "Structure and content of the visible Darknet",
		Conference:     ARXIV,
		ConferenceYear: 2018,
		Authors:        []string{"Zeta Avarikioti", "Roman Brunner", "Aggelos Kiayias", "Roger Wattenhofer", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1811.01348.pdf",
		Tags:           []Tag{},
		Citations:      26,
	},
	{
		Handle:         "fnf-bft",
		Name:           "FnF-BFT: A BFT Protocol with Provable Performance Under Attack",
		Conference:     SIROCCO,
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Lioba Heimbach", "Roland Schmid", "Laurent Vanbever", "Roger Wattenhofer", "Patrick Wintermeyer"},
		Url:            "https://tik-old.ee.ethz.ch/file/34168cbbbcfa75bf48c87a84844b3ae9/FnF_BFT__SIROCCO_2023_-1.pdf",
		Tags:           []Tag{},
		Citations:      29,
	},
	{
		Handle:         "bitcoin-temporary-dishonest-majority",
		Name:           "Bitcoin Security under Temporary Dishonest Majority",
		Conference:     FC,
		ConferenceYear: 2019,
		Authors:        []string{"Zeta Avarikioti", "Lukas Käppeli", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1908.00427.pdf",
		Tags:           []Tag{}, //keywords : Bitcoin, Security, Dishonest Majority, Offline Players, Sleepy Model
		Citations:      23,
	},
	{
		Handle:         "hide-and-seek",
		Name:           "Hide & Seek: Privacy-Preserving Rebalancing on Payment Channel Networks",
		Conference:     FC,
		ConferenceYear: 2022,
		Authors:        []string{"Zeta Avarikioti", "Krzysztof Pietrzak", "Iosif Salem", "Stefan Schmid", "Samarth Tiwari", "Michelle Yeo"},
		Url:            "https://arxiv.org/pdf/2110.08848.pdf",
		Tags:           []Tag{}, //keywords : Payment Channel Networks, Privacy, Rebalancing.
		Citations:      25,
	},
	{
		Handle:     "tx-chain",
		Name:       "TxChain: Efficient Cryptocurrency Light Clients via Contingent Transaction Aggregation",
		Conference: DPMCBT,
		Authors:    []string{"Alexei Zamyatin", "Zeta Avarikioti", "Daniel Perez", "William J. Knottenbelt"},
		Url:        "https://eprint.iacr.org/2020/580.pdf",
		Tags:       []Tag{LIGHT_CLIENTS},
		Citations:  15,
	},
	{
		Handle:     "payment-networks-as-creation-games",
		Name:       "Payment Networks as Creation Games",
		Conference: DPMCBT,
		Authors:    []string{"Zeta Avarikioti", "Rolf Scheuner", "Roger Wattenhofer"},
		Url:        "https://arxiv.org/pdf/1908.00436.pdf",
		Tags:       []Tag{PAYMENT_CHANNELS},
		Citations:  15,
	},
	{
		Handle:         "algorithmic-channel-design",
		Name:           "Algorithmic channel design",
		Conference:     ISAAC,
		ConferenceYear: 2018,
		Authors:        []string{"Zeta Avarikioti", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/336835/1/LIPIcs-ISAAC-2018-16.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      17,
	},
	{
		Handle:         "high-dimensional-approximate-r-nets",
		Name:           "High-dimensional approximate r-nets",
		Conference:     ALGORITHMICA,
		ConferenceYear: 2020,
		Authors:        []string{"Zeta Avarikioti", "Ioannis Z Emiris", "Loukas Kavouras", "Ioannis Psarros"},
		Url:            "https://epubs.siam.org/doi/pdf/10.1137/1.9781611974782.2",
		Tags:           []Tag{},
		Citations:      7,
	},
	{
		Handle:         "approximate-near-neighbors-in-high-dimension",
		Name:           "Practical linear-space Approximate Near Neighbors in high dimension",
		Conference:     ARXIV,
		ConferenceYear: 2016,
		Authors:        []string{"Zeta Avarikioti", "Ioannis Z Emiris", "Ioannis Psarros", "Georgios Samaras"},
		Url:            "https://arxiv.org/pdf/1612.07405.pdf",
		Tags:           []Tag{},
		Citations:      7,
	},
	{
		Handle:         "game-theoretic-analysis-of-off-chain-protocols",
		Name:           "Towards a game-theoretic security analysis of off-chain protocols",
		Conference:     CSF,
		ConferenceYear: 2023,
		Authors:        []string{"Sophie Rain", "Zeta Avarikioti", "Laura Kovács", "Matteo Maffei"},
		Url:            "https://arxiv.org/pdf/2109.07429.pdf",
		Tags:           []Tag{},
		Citations:      11,
	},
	{
		Handle:         "suborn-channels",
		Name:           "Suborn Channels: Incentives Against Timelock Bribes",
		Conference:     FC,
		ConferenceYear: 2022,
		Authors:        []string{"Zeta Avarikioti", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://eprint.iacr.org/2022/814.pdf",
		Tags:           []Tag{LIGHTNING_NETWORK, BITCOIN, PAYMENT_CHANNELS},
		Citations:      7,
	},
	{
		Handle:         "wiser",
		Name:           "Wiser: Increasing Throughput in Payment Channel Networks with Transaction Aggregation",
		Conference:     AFT,
		ConferenceYear: 2022,
		Authors:        []string{"Samarth Tiwari", "Michelle Yeo", "Zeta Avarikioti", "Iosif Salem", "Krzysztof Pietrzak", "Stefan Schmid"},
		Url:            "https://arxiv.org/pdf/2205.11597.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, PRIVACY},
		Citations:      3,
	},
	{
		Handle:         "lightning-ceration-games",
		Name:           "Lightning Creation Games",
		Conference:     ICDCS,
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Tomasz Lizurej", "Tomasz Michalak", "Michelle Yeo"},
		Url:            "https://arxiv.org/pdf/2306.16006.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS, BITCOIN},
		Citations:      2,
	},
	{
		Handle:         "pos-sidechains",
		Name:           "Proof-of-Stake Sidechains",
		Conference:     SP,
		ConferenceYear: 2019,
		Authors:        []string{"Peter Gaži", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2018/1239.pdf",
		Tags:           []Tag{PROOF_OF_STAKE, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      244,
	},
	{
		Handle:         "sok-distributed-ledger-communication",
		Name:           "SoK: Communication across distributed ledgers",
		Conference:     FC,
		ConferenceYear: 2021,
		Authors:        []string{"Alexei Zamyatin", "Mustafa Al-Bassam", "Dionysis Zindros", "Eleftherios Kokoris-Kogias", "Pedro Moreno-Sanchez", "Aggelos Kiayias", "William J Knottenbelt"},
		Url:            "https://eprint.iacr.org/2019/1128.pdf",
		Tags:           []Tag{INTEROPERABILITY},
		Citations:      191,
	},
	{
		Handle:         "proof-of-burn",
		Name:           "Proof-of-Burn",
		Conference:     FC,
		ConferenceYear: 2020,
		Authors:        []string{"Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2019/1096.pdf",
		Tags:           []Tag{},
		Citations:      167,
	},
	{
		Handle:         "pow-sidechains",
		Name:           "Proof-of-Work Sidechains",
		Conference:     FC,
		ConferenceYear: 2019,
		Authors:        []string{"Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2018/1048.pdf",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      148,
	},
	{
		Handle:         "trust-is-risk",
		Name:           "Trust is Risk: A Decentralized Financial Trust Platform",
		Conference:     FC,
		ConferenceYear: 2017,
		Authors:        []string{"Orfeas Stefanos Thyfronitis Litos", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2017/156.pdf",
		Tags:           []Tag{BITCOIN},
		Citations:      25,
	},
	{
		Handle:         "updatable-blockchains",
		Name:           "Updatable Blockchains",
		Conference:     ESORICS,
		ConferenceYear: 2020,
		Authors:        []string{"Michele Ciampi", "Nikos Karayannidis", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/887.pdf",
		Tags:           []Tag{},
		Citations:      17,
	},
	{
		Handle:         "cryptocurrency-egalitarianism",
		Name:           "Cryptocurrency Egalitarianism: A Quantitative Approach",
		Conference:     TOKENOMICS,
		ConferenceYear: 2019,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Christos Nasikas", "Dionysis Zindros"},
		Url:            "https://arxiv.org/pdf/1907.02434",
		Tags:           []Tag{PROOF_OF_WORK, PROOF_OF_STAKE},
		Citations:      19,
	},
	{
		Handle:         "superblock-compact-storage-for-nipopows",
		Name:           "Compact storage of superblocks for NiPoPoW applications",
		Conference:     MARBLE,
		ConferenceYear: 2019,
		Authors:        []string{"Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2019/1444.pdf",
		Tags:           []Tag{PROOF_OF_WORK, INTEROPERABILITY},
		Citations:      19,
	},
	{
		Handle:         "gas-efficient-superlight-client",
		Name:           "A Gas-Efficient Superlight Bitcoin Client in Solidity",
		Conference:     AFT,
		ConferenceYear: 2020,
		Authors:        []string{"Stelios Daveas", "Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/927.pdf",
		Tags:           []Tag{PROOF_OF_WORK, BITCOIN, SMART_CONTRACTS},
		Citations:      17,
	},
	{
		Handle:         "logspace-mining",
		Name:           "Mining in Logarithmic Space",
		Conference:     SIGSAC,
		ConferenceYear: 2021,
		Authors:        []string{"Aggelos Kiayias", "Nikos Leonardos", "Dionysis Zindros"},
		Url:            "https://dl.acm.org/doi/pdf/10.1145/3460120.3484784",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      16,
	},
	{
		Handle:         "ddh-ring-signatures",
		Name:           "Short Accountable Ring Signatures Based on DDH",
		Conference:     ESORICS,
		ConferenceYear: 2015,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth", "Christophe Petit"},
		Url:            "https://eprint.iacr.org/2015/643.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES},
		Citations:      143,
	},
	{
		Handle:         "beleniosrf",
		Name:           "BeleniosRF: A Non-Interactive Receipt-Free Electronic Voting Scheme",
		Conference:     SIGSAC,
		ConferenceYear: 2016,
		Authors:        []string{"Pyrros Chaidos", "Véronique Cortier", "Georg Fuchsbauer", "David Galindo"},
		Url:            "https://eprint.iacr.org/2015/629.pdf",
		Tags:           []Tag{VOTING},
		Citations:      104,
	},
	{
		Handle:         "arithmetization-oriented-hash-functions",
		Name:           "New Design Techniques for Efficient Arithmetization-Oriented Hash Functions: Anemoi Permutations and Jive Compression Mode",
		Conference:     CRYPTO,
		ConferenceYear: 2023,
		Authors:        []string{"Clémence Bouvier1", "Pierre Briaud", "Pyrros Chaidos", "Léo Perrin", "Robin Salen", "Vesselin Velichkov", "Danny Willems"},
		Url:            "https://eprint.iacr.org/2022/840.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
		Citations:      29,
	},
	{
		Handle:         "designated-verifier-nizkp",
		Name:           "Efficient Designated-Verifier Non-interactive Zero-Knowledge Proofs of Knowledge",
		Conference:     EUROCRYPT,
		ConferenceYear: 2018,
		Authors:        []string{"Pyrros Chaidos", "Geoffroy Couteau"},
		Url:            "https://eprint.iacr.org/2017/1029.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE},
		Citations:      36,
	},
	{
		Handle:         "non-interactive-sigmas-without-ro",
		Name:           "Making Sigma-protocols Non-interactive without Random Oracles",
		Conference:     PKC,
		ConferenceYear: 2015,
		Authors:        []string{"Pyrros Chaidos", "Jens Groth"},
		Url:            "https://www.iacr.org/archive/pkc2015/90200192/90200192.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, VOTING},
		Citations:      33,
	},
	{
		Handle:         "efficient-zkp-systems",
		Name:           "Efficient Zero-Knowledge Proof Systems",
		Conference:     FOSAD,
		ConferenceYear: 2015,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Jens Groth"},
		Url:            "https://jbootle.github.io/Misc/fosad2015.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, COMMITMENTS},
		Citations:      29,
	},
	{
		Handle:         "mithril",
		Name:           "Mithril: Stake-based Threshold Multisignatures",
		Conference:     EPRINT,
		ConferenceYear: 2021,
		Authors:        []string{"Pyrros Chaidos", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2021/916.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES, UC},
		Citations:      15,
	},
	{
		Handle:         "fully-dynamic-group-signatures",
		Name:           "Foundations of Fully Dynamic Group Signatures",
		Conference:     ACNS,
		ConferenceYear: 2016,
		Authors:        []string{"Jonathan Bootle", "Andrea Cerulli", "Pyrros Chaidos", "Essam Ghadafi", "Jens Groth"},
		Url:            "https://eprint.iacr.org/2016/368.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      129,
	},
	{
		Handle:         "divertibility-to-bling-ballot-copying-in-helios",
		Name:           "Applying Divertibility to Blind Ballot Copying in the Helios Internet Voting System",
		Conference:     ESORICS,
		ConferenceYear: 2012,
		Authors:        []string{"Yvo Desmedt", "Pyrros Chaidos"},
		Url:            "http://www0.cs.ucl.ac.uk/staff/P.Chaidos/helios-esorics-cr.pdf",
		Tags:           []Tag{VOTING, PRIVACY},
		Citations:      18,
	},
	{
		Handle:         "pow-checkpointing",
		Name:           "Securing Proof-of-Work Ledgers via Checkpointing",
		Conference:     ICBC,
		ConferenceYear: 2021,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias"},
		Url:            "https://eprint.iacr.org/2020/173.pdf",
		Tags:           []Tag{PROOF_OF_WORK},
		Citations:      35,
	},
	{
		Handle:         "sok-decentralization",
		Name:           "SoK: A Stratified Approach to Blockchain Decentralization",
		Conference:     EPRINT,
		ConferenceYear: 2022,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Christina Ovezik"},
		Url:            "https://arxiv.org/pdf/2211.01291.pdf",
		Tags:           []Tag{DECENTRALIZATION},
		Citations:      15,
	},
	{
		Handle:         "pos-account-management",
		Name:           "Account Management in Proof of Stake Ledgers",
		Conference:     SCN,
		ConferenceYear: 2020,
		Authors:        []string{"Dimitris Karakostas", "Aggelos Kiayias", "Mario Larangeira"},
		Url:            "https://eprint.iacr.org/2020/525.pdf",
		Tags:           []Tag{PROOF_OF_STAKE},
		Citations:      11,
	},
	{
		Handle:         "puff-of-steem",
		Name:           "A Puff of Steem: Security Analysis of Decentralized Content Curation",
		Conference:     TOKENOMICS,
		ConferenceYear: 2019,
		Authors:        []string{"Aggelos Kiayias", "Benjamin Livshits", "Andrés Monteoliva Mosteiro", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://www.pure.ed.ac.uk/ws/portalfiles/portal/129969711/A_Puff_of_Steem_KIAYIAS_DOA13012020_VOR_CC_BY.pdf",
		Tags:           []Tag{DECENTRALIZATION},
		Citations:      22,
	},
	{
		Handle:         "trust-strangers",
		Name:           "How to Trust Strangers: Composition of Byzantine Quorum Systems",
		Conference:     SRDS,
		ConferenceYear: 2021,
		Authors:        []string{"Orestis Alpos", "Christian Cachin", "Luca Zanolini"},
		Url:            "https://arxiv.org/pdf/2107.11331",
		Tags:           []Tag{CONSENSUS},
		Citations:      16,
	},
	{
		Handle:         "eating-sandwiches",
		Name:           "Eating sandwiches: Modular and lightweight elimination of transaction reordering attacks",
		Conference:     ARXIV,
		ConferenceYear: 2023,
		Authors:        []string{"Orestis Alpos", "Ignacio Amores-Sesar", "Christian Cachin", "Michelle Yeo"},
		Url:            "https://arxiv.org/pdf/2307.02954",
		Tags:           []Tag{MEV, FRONT_RUNNING},
		Citations:      7,
	},
	{
		Handle:         "sync-power",
		Name:           "On the Synchronization Power of Token Smart Contracts",
		Conference:     ICDCS,
		ConferenceYear: 2021,
		Authors:        []string{"Orestis Alpos", "Christian Cachin", "Giorgia Azzurra Marson", "Luca Zanolini"},
		Url:            "https://arxiv.org/pdf/2101.05543",
		Tags:           []Tag{SMART_CONTRACTS},
		Citations:      8,
	},
	{
		Handle:         "consensus-beyond-thresholds",
		Name:           "Consensus Beyond Thresholds: Generalized Byzantine Quorums Made Live",
		Conference:     SRDS,
		ConferenceYear: 2020,
		Authors:        []string{"Orestis Alpos", "Christian Cachin"},
		Url:            "https://arxiv.org/pdf/2006.04616",
		Tags:           []Tag{CONSENSUS},
		Citations:      7,
	},
	{
		Handle:         "pos-atob",
		Name:           "Practical Large-Scale Proof-of-Stake Asynchronous Total-Order Broadcast",
		Conference:     EPRINT,
		ConferenceYear: 2023,
		Authors:        []string{"Orestis Alpos", "Christian Cachin", "Simon Holmgaard Kamp", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2023/1103.pdf",
		Tags:           []Tag{CONSENSUS, PROOF_OF_STAKE},
		Citations:      5,
	},
	{
		Handle:         "dske",
		Name:           "DSKE: Digital Signatures with Key Extraction",
		Conference:     EPRINT,
		ConferenceYear: 2022,
		Authors:        []string{"Orestis Alpos", "Christian Cachin", "Simon Holmgaard Kamp", "Jesper Buus Nielsen"},
		Url:            "https://eprint.iacr.org/2022/1753.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      3,
	},
	{
		Handle:         "thetacrypt",
		Name:           "Thetacrypt: A Distributed Service for Threshold Cryptography On-Demand",
		Conference:     MIDDLEWARE,
		ConferenceYear: 2023,
		Authors:        []string{"Orestis Alpos", "Mariarosaria Barbaraci", "Christian Cachin", "Noah Schmid", "Michael Senn"},
		Url:            "https://dl.acm.org/doi/pdf/10.1145/3626564.3629100",
		Tags:           []Tag{},
		Citations:      1,
	},
	{
		Handle:         "do-not-trust-in-numbers",
		Name:           "Do Not Trust in Numbers: Practical Distributed Cryptography With General Trust",
		Conference:     SSS,
		ConferenceYear: 2023,
		Authors:        []string{"Orestis Alpos", "Christian Cachin"},
		Url:            "https://eprint.iacr.org/2022/1767.pdf",
		Tags:           []Tag{},
		Citations:      1,
	},
	{
		Handle:         "lazy-light-clients",
		Name:           "Light Clients for Lazy Blockchains",
		Conference:     FC,
		ConferenceYear: 2024,
		Authors:        []string{"Ertem Nusret Tas", "Dionysis Zindros", "Lei Yang", "David Tse"},
		Url:            "https://arxiv.org/pdf/2203.15968v2",
		Tags:           []Tag{LIGHT_CLIENTS},
		Citations:      8,
	},
	{
		Handle:         "hours-of-horus",
		Name:           "Hours of Horus: Keyless Cryptocurrency Wallets",
		Conference:     FC,
		ConferenceYear: 2022,
		Authors:        []string{"Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2021/715.pdf",
		Tags:           []Tag{WALLETS, TIMELOCK, WITNESS_ENCRYPTION},
		Citations:      3,
	},
	{
		Handle:         "better-safe-than-sorry",
		Name:           "Better Safe than Sorry: Recovering after Adversarial Majority",
		Conference:     ARXIV,
		ConferenceYear: 2023,
		Authors:        []string{"Srivatsan Sridhar", "Dionysis Zindros", "David Tse"},
		Url:            "https://arxiv.org/pdf/2310.06338",
		Tags:           []Tag{CONSENSUS},
		Citations:      1,
	},
	{
		Handle:         "rollerblade",
		Name:           "Rollerblade: Replicated Distributed Protocol Emulation on Top of Ledgers",
		Conference:     EPRINT,
		ConferenceYear: 2024,
		Authors:        []string{"Dionysis Zindros", "Apostolos Tzinas", "David Tse"},
		Url:            "https://eprint.iacr.org/2024/210.pdf",
		Tags:           []Tag{},
		Citations:      0,
	},
	{
		Handle:         "cassiopeia",
		Name:           "Cassiopeia: Practical On-Chain Witness Encryption",
		Conference:     FC,
		ConferenceYear: 2023,
		Authors:        []string{"Schwinn Saereesitthipitak", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2023/635.pdf",
		Tags:           []Tag{WITNESS_ENCRYPTION, PVSS, SMART_CONTRACTS},
		Citations:      0,
	},
	{
		Handle:         "smart-contract-derivatives",
		Name:           "Smart Contract Derivatives",
		Conference:     MARBLE,
		ConferenceYear: 2020,
		Authors:        []string{"Kostis Karantias", "Aggelos Kiayias", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/138.pdf",
		Tags:           []Tag{SMART_CONTRACTS},
		Citations:      10,
	},
	{
		Handle:         "velvet-path-to-superlight",
		Name:           "The Velvet Path to Superlight Blockchain Clients",
		Conference:     AFT,
		ConferenceYear: 2021,
		Authors:        []string{"Aggelos Kiayias", "Andrianna Polydouri", "Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2020/1122.pdf",
		Tags:           []Tag{LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      11,
	},
	{
		Handle:         "soft-power",
		Name:           "Soft Power: Upgrading Chain Macroeconomic Policy Through Soft Forks",
		Conference:     FCWTS,
		ConferenceYear: 2021,
		Authors:        []string{"Dionysis Zindros"},
		Url:            "https://eprint.iacr.org/2021/577.pdf",
		Tags:           []Tag{SMART_CONTRACTS},
		Citations:      5,
	},
	{
		Handle:         "channels-route-discovery",
		Name:           "Route Discovery in Private Payment Channel Networks",
		Conference:     EPRINT,
		ConferenceYear: 2021,
		Authors:        []string{"Zeta Avarikioti", "Mahsa Bastankhah", "Mohammad Ali Maddah-Ali", "Krzysztof Pietrzak", "Jakub Svoboda", "Michelle Yeo"},
		Url:            "https://eprint.iacr.org/2021/1539.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      2,
	},
	{
		Handle:         "r-nets-clustering",
		Name:           "High Dimensional Clustering with r-nets",
		Conference:     AAAI,
		ConferenceYear: 2019,
		Authors:        []string{"Zeta Avarikioti", "Alain Ryser", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://ojs.aaai.org/index.php/AAAI/article/view/4189/4067",
		Tags:           []Tag{},
		Citations:      1,
	},
	{
		Handle:         "online-payment-network-design",
		Name:           "Online Payment Network Design",
		Conference:     ESORICS,
		ConferenceYear: 2019,
		Authors:        []string{"Zeta Avarikioti", "Kenan Besic", "Yuyi Wang", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/1908.00432",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      1,
	},
	{
		Handle:         "bribe-and-fork",
		Name:           "Bribe & Fork: Cheap Bribing Attacks via Forking Threat",
		Conference:     ARXIV,
		ConferenceYear: 2024,
		Authors:        []string{"Zeta Avarikioti", "Paweł Kędzior", "Tomasz Lizurej", "Tomasz Michalak"},
		Url:            "https://arxiv.org/pdf/2402.01363v1",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      0,
	},
	{
		Handle:         "musketeer",
		Name:           "Musketeer: Incentive-Compatible Rebalancing for Payment Channel Networks",
		Conference:     EPRINT,
		ConferenceYear: 2023,
		Authors:        []string{"Zeta Avarikioti", "Stefan Schmid", "Samarth Tiwari"},
		Url:            "https://eprint.iacr.org/2023/938.pdf",
		Tags:           []Tag{PAYMENT_CHANNELS},
		Citations:      0,
	},
	{
		Handle:         "glimpse",
		Name:           "Glimpse: On-Demand PoW Light Client with Constant-Size Storage for DeFi",
		Conference:     USENIX,
		ConferenceYear: 2023,
		Authors:        []string{"Giulia Scaffino", "Lukas Aumayr", "Zeta Avarikioti", "Matteo Maffei"},
		Url:            "https://www.usenix.org/system/files/usenixsecurity23-scaffino.pdf",
		Tags:           []Tag{PROOF_OF_WORK, LIGHT_CLIENTS, INTEROPERABILITY},
		Citations:      4,
	},
	{
		Handle:         "anonymous-tokens",
		Name:           "Blind Multisignatures for Anonymous Tokens with Decentralized Issuance",
		Conference:     CCS,
		ConferenceYear: 2024,
		Authors:        []string{"Ioanna Karantaidou", "Omar Renawi", "Foteini Baldimtsi", "Nikolaos Kamarinakis", "Jonathan Katz", "Julian Loss"},
		Url:            "https://eprint.iacr.org/2024/1406.pdf",
		Tags:           []Tag{SIGNATURES, PRIVACY, DECENTRALIZATION},
		Citations:      5,
	},
	{
		Handle:         "clementine",
		Name:           "Clementine: A Collateral-Efficient, Trust-Minimized, and Scalable Bitcoin Bridge",
		Conference:     EPRINT,
		ConferenceYear: 2025,
		Authors:        []string{"Ekrem Bal", "Lukas Aumayr", "Atacan İyidoğan", "Giulia Scaffino", "Hakan Karakuş", "Cengiz Eray Aslan", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://eprint.iacr.org/2025/776.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, BITCOIN},
		Citations:      0,
	},
	{
		Handle:         "bridgeless",
		Name:           "Formalization and security analysis of the Bridgeless protocol",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Orestis Alpos", "Oleg Fomenko", "Dimitris Karakostas", "Oleksandr Kurbatov", "Andrey Sabelnikov"},
		Url:            "https://arxiv.org/pdf/2506.19730",
		Tags:           []Tag{INTEROPERABILITY},
		Citations:      0,
	},
	{
		Handle:         "xtransfer",
		Name:           "X-Transfer: Enabling and optimizing cross-PCN transactions",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Iosif Salem", "Stefan Schmid", "Michelle Yeo"},
		Url:            "https://eprint.iacr.org/2025/272.pdf",
		Tags:           []Tag{INTEROPERABILITY, PAYMENT_CHANNELS},
		Citations:      2,
	},
	{
		Handle:         "verified-lightning-network",
		Name:           "A Formally Verified Lightning Network",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Grzegorz Fabiański", "Rafał Stefański", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://arxiv.org/pdf/2503.07200",
		Tags:           []Tag{LIGHTNING_NETWORK, BITCOIN},
		Citations:      1,
	},
	{
		Handle:         "consensus-under-adversary-majority",
		Name:           "Consensus Under Adversary Majority Done Right",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Srivatsan Sridhar", "Ertem Nusret Tas", "Joachim Neu", "Dionysis Zindros", "David Tse"},
		Url:            "https://arxiv.org/pdf/2411.01689",
		Tags:           []Tag{CONSENSUS, INTEROPERABILITY},
		Citations:      2,
	},
	{
		Handle:         "bitvm2",
		Name:           "Bridging Bitcoin to Second Layers via BitVM2",
		Conference:     EPRINT,
		ConferenceYear: 2025,
		Authors:        []string{"Robin Linus", "Lukas Aumayr", "Zeta Avarikioti", "Matteo Maffei", "Andrea Pelosi", "Orfeas Stefanos Thyfronitis Litos", "Christos Stefo", "David Tse", "Alexei Zamyatin"},
		Url:            "https://eprint.iacr.org/2025/1158.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, INTEROPERABILITY, BITCOIN},
		Citations:      0,
	},
	{
		Handle:         "bitvm",
		Name:           "BitVM: Quasi-Turing Complete Computation on Bitcoin",
		Conference:     EPRINT,
		ConferenceYear: 2024,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Robin Linus", "Matteo Maffei", "Andrea Pelosi", "Christos Stefo", "Alexei Zamyatin"},
		Url:            "https://eprint.iacr.org/2024/1995.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, INTEROPERABILITY, BITCOIN},
		Citations:      4,
	},
	{
		Handle:         "optimal-reward-allocation",
		Name:           "Optimal Reward Allocation via Proportional Splitting",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Dimitris Karakostas", "Karl Kreder", "Shreekara Shastry"},
		Url:            "https://arxiv.org/pdf/2503.10185",
		Tags:           []Tag{FAIRNESS, PROOF_OF_WORK},
		Citations:      0,
	},
	{
		Handle:         "post-quantum-threshold-signatures",
		Name:           "Post-Quantum Threshold Ring Signature Applications from VOLE-in-the-Head",
		Conference:     CCS,
		ConferenceYear: 2025,
		Authors:        []string{"James Hsin-yu Chiang", "Ivan Damgård", "William R. Duro", "Sunniva Engan", "Sebastian Kolby", "Peter Scholl"},
		Url:            "https://eprint.iacr.org/2025/113.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES},
		Citations:      0,
	},
	{
		Handle:         "sok-measuring-blockchain-decentralization",
		Name:           "SoK: Measuring Blockchain Decentralization",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Christina Ovezik", "Dimitris Karakostas", "Mary Milad", "Aggelos Kiayias", "Daniel W. Woods"},
		Url:            "https://arxiv.org/pdf/2501.18279",
		Tags:           []Tag{DECENTRALIZATION},
		Citations:      1,
	},
	{
		Handle:         "measuring-aritrage-losses",
		Name:           "Measuring Arbitrage Losses and Profitability of AMM Liquidity",
		Conference:     ARXIV,
		ConferenceYear: 2024,
		Authors:        []string{"Robin Fritsch", "Andrea Canidio"},
		Url:            "https://arxiv.org/pdf/2404.05803",
		Tags:           []Tag{DEFI},
		Citations:      15,
	},
	{
		Handle:         "sok-attack-on-daos",
		Name:           "Sok: Attacks on DAOs",
		Conference:     ARXIV,
		ConferenceYear: 2024,
		Authors:        []string{"Rainer Feichtinger", "Robin Fritsch", "Lioba Heimbach", "Yann Vonlanthen", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/2406.15071",
		Tags:           []Tag{DEFI},
		Citations:      15,
	},
	{
		Handle:         "glacius",
		Name:           "Glacius: Threshold schnorr signatures from DDH with full adaptive security",
		Conference:     EUROCRYPT,
		ConferenceYear: 2025,
		Authors:        []string{"Renas Bacho", "Sourav Das", "Julian Loss", "Ling Ren"},
		Url:            "https://eprint.iacr.org/2024/1628.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      5,
	},
	{
		Handle:         "anonymous-tokens",
		Name:           "Blind Multisignatures for Anonymous Tokens with Decentralized Issuance",
		Conference:     CCS,
		ConferenceYear: 2024,
		Authors:        []string{"Ioanna Karantaidou", "Omar Renawi", "Foteini Baldimtsi", "Nikolaos Kamarinakis", "Jonathan Katz", "Julian Loss"},
		Url:            "https://eprint.iacr.org/2024/1406.pdf",
		Tags:           []Tag{SIGNATURES, PRIVACY, DECENTRALIZATION},
		Citations:      5,
	},
	{
		Handle:         "clementine",
		Name:           "Clementine: A Collateral-Efficient, Trust-Minimized, and Scalable Bitcoin Bridge",
		Conference:     EPRINT,
		ConferenceYear: 2025,
		Authors:        []string{"Ekrem Bal", "Lukas Aumayr", "Atacan İyidoğan", "Giulia Scaffino", "Hakan Karakuş", "Cengiz Eray Aslan", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://eprint.iacr.org/2025/776.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, BITCOIN},
		Citations:      0,
	},
	{
		Handle:         "bridgeless",
		Name:           "Formalization and security analysis of the Bridgeless protocol",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Orestis Alpos", "Oleg Fomenko", "Dimitris Karakostas", "Oleksandr Kurbatov", "Andrey Sabelnikov"},
		Url:            "https://arxiv.org/pdf/2506.19730",
		Tags:           []Tag{INTEROPERABILITY},
		Citations:      0,
	},
	{
		Handle:         "xtransfer",
		Name:           "X-Transfer: Enabling and optimizing cross-PCN transactions",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Iosif Salem", "Stefan Schmid", "Michelle Yeo"},
		Url:            "https://eprint.iacr.org/2025/272.pdf",
		Tags:           []Tag{INTEROPERABILITY, PAYMENT_CHANNELS},
		Citations:      2,
	},
	{
		Handle:         "verified-lightning-network",
		Name:           "A Formally Verified Lightning Network",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Grzegorz Fabiański", "Rafał Stefański", "Orfeas Stefanos Thyfronitis Litos"},
		Url:            "https://arxiv.org/pdf/2503.07200",
		Tags:           []Tag{LIGHTNING_NETWORK, BITCOIN},
		Citations:      1,
	},
	{
		Handle:         "consensus-under-adversary-majority",
		Name:           "Consensus Under Adversary Majority Done Right",
		Conference:     FC,
		ConferenceYear: 2025,
		Authors:        []string{"Srivatsan Sridhar", "Ertem Nusret Tas", "Joachim Neu", "Dionysis Zindros", "David Tse"},
		Url:            "https://arxiv.org/pdf/2411.01689",
		Tags:           []Tag{CONSENSUS, INTEROPERABILITY},
		Citations:      2,
	},
	{
		Handle:         "bitvm2",
		Name:           "Bridging Bitcoin to Second Layers via BitVM2",
		Conference:     EPRINT,
		ConferenceYear: 2025,
		Authors:        []string{"Robin Linus", "Lukas Aumayr", "Zeta Avarikioti", "Matteo Maffei", "Andrea Pelosi", "Orfeas Stefanos Thyfronitis Litos", "Christos Stefo", "David Tse", "Alexei Zamyatin"},
		Url:            "https://eprint.iacr.org/2025/1158.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, INTEROPERABILITY, BITCOIN},
		Citations:      0,
	},
	{
		Handle:         "bitvm",
		Name:           "BitVM: Quasi-Turing Complete Computation on Bitcoin",
		Conference:     EPRINT,
		ConferenceYear: 2024,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Robin Linus", "Matteo Maffei", "Andrea Pelosi", "Christos Stefo", "Alexei Zamyatin"},
		Url:            "https://eprint.iacr.org/2024/1995.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, INTEROPERABILITY, BITCOIN},
		Citations:      4,
	},
	{
		Handle:         "optimal-reward-allocation",
		Name:           "Optimal Reward Allocation via Proportional Splitting",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Lukas Aumayr", "Zeta Avarikioti", "Dimitris Karakostas", "Karl Kreder", "Shreekara Shastry"},
		Url:            "https://arxiv.org/pdf/2503.10185",
		Tags:           []Tag{FAIRNESS, PROOF_OF_WORK},
		Citations:      0,
	},
	{
		Handle:         "post-quantum-threshold-signatures",
		Name:           "Post-Quantum Threshold Ring Signature Applications from VOLE-in-the-Head",
		Conference:     CCS,
		ConferenceYear: 2025,
		Authors:        []string{"James Hsin-yu Chiang", "Ivan Damgård", "William R. Duro", "Sunniva Engan", "Sebastian Kolby", "Peter Scholl"},
		Url:            "https://eprint.iacr.org/2025/113.pdf",
		Tags:           []Tag{ZERO_KNOWLEDGE, SIGNATURES},
		Citations:      0,
	},
	{
		Handle:         "sok-measuring-blockchain-decentralization",
		Name:           "SoK: Measuring Blockchain Decentralization",
		Conference:     ARXIV,
		ConferenceYear: 2025,
		Authors:        []string{"Christina Ovezik", "Dimitris Karakostas", "Mary Milad", "Aggelos Kiayias", "Daniel W. Woods"},
		Url:            "https://arxiv.org/pdf/2501.18279",
		Tags:           []Tag{DECENTRALIZATION},
		Citations:      1,
	},
	{
		Handle:         "measuring-aritrage-losses",
		Name:           "Measuring Arbitrage Losses and Profitability of AMM Liquidity",
		Conference:     ARXIV,
		ConferenceYear: 2024,
		Authors:        []string{"Robin Fritsch", "Andrea Canidio"},
		Url:            "https://arxiv.org/pdf/2404.05803",
		Tags:           []Tag{DEFI},
		Citations:      15,
	},
	{
		Handle:         "sok-attack-on-daos",
		Name:           "Sok: Attacks on DAOs",
		Conference:     ARXIV,
		ConferenceYear: 2024,
		Authors:        []string{"Rainer Feichtinger", "Robin Fritsch", "Lioba Heimbach", "Yann Vonlanthen", "Roger Wattenhofer"},
		Url:            "https://arxiv.org/pdf/2406.15071",
		Tags:           []Tag{DEFI},
		Citations:      15,
	},
	{
		Handle:         "glacius",
		Name:           "Glacius: Threshold schnorr signatures from DDH with full adaptive security",
		Conference:     EUROCRYPT,
		ConferenceYear: 2025,
		Authors:        []string{"Renas Bacho", "Sourav Das", "Julian Loss", "Ling Ren"},
		Url:            "https://eprint.iacr.org/2024/1628.pdf",
		Tags:           []Tag{SIGNATURES},
		Citations:      5,
	},
}
